import dayjs from 'dayjs';
import { saveAs } from 'file-saver';
import { formatValue } from './payrollFormatters';

/**
 * Spreadsheet export of a month's salary slip.
 *
 * The Excel sheet is a faithful replica of the PDF salary slip — same header,
 * pay-period bar, employee block, summary cards, A/B earnings and 1/2 deductions
 * panels, salary history, metadata and the authorised-signatory block — rebuilt
 * with merged cells and LIVE FORMULAS:
 *
 *   • line amount   = quantity × rate            (hours/days and rates are real numbers,
 *                                                 the unit is carried by the number format)
 *   • subtotals     = SUM(range)
 *   • gross         = variable subtotal + fixed subtotal
 *   • statutory     = base × percentage
 *   • deductions    = attendance + statutory
 *   • net payable   = gross − deductions
 *   • remaining     = payable − payments so far
 *
 * A formula is only written when its computed result matches the payroll engine's
 * own figure to the rupee; otherwise the engine value is written literally, so the
 * workbook can never disagree with the official slip.
 */

// ─── Input ────────────────────────────────────────────────────────────────────

export interface SalarySlipExportInput {
    employee: any;
    /** Raw monthly salary record from the payroll API */
    apiSalaryData: any;
    /** Totals from useSalaryCalculations */
    summaryData?: any;
    /** Payment ledger rows from useSalaryCalculations */
    paymentRows?: any[];
    month: number;
    year: number;
    /** Company overview record — header branding, logo, stamp, signatory name */
    company?: any;
    /** Name shown against "Generated By" */
    generatedBy?: string;
    resolveName?: (name: string) => string;
    resolveComponent?: (name: string) => any | null;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const num = (v: any): number => {
    const n = Number(v);
    return Number.isFinite(n) ? n : 0;
};

const safe = (v: any, fallback = '—'): string => {
    const s = v === null || v === undefined ? '' : String(v).trim();
    return !s || s === 'N/A' || s === 'null' || s === 'undefined' ? fallback : s;
};

const maskAcct = (acct: any): string => {
    const s = safe(acct, '');
    return s.length < 4 ? '—' : `**** ${s.slice(-4)}`;
};

const fmtDate = (v: any, withTime = false): string => {
    if (!v) return '—';
    const d = dayjs(v);
    return d.isValid() ? d.format(withTime ? 'DD MMM YYYY, hh:mm A' : 'DD MMM YYYY') : String(v);
};

const money2 = (n: number) => `₹${num(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

/** A number when the value is one, otherwise an em-dash — keeps day counts numeric in the sheet. */
const numOrDash = (v: any): number | string => {
    if (v === null || v === undefined || v === '') return '—';
    const n = Number(v);
    return Number.isFinite(n) ? n : safe(v);
};

interface ParsedQty {
    qty: number;
    /** The unit the engine itself declared, when the value carried one. */
    unit: 'Hrs' | 'Days' | '';
}

/**
 * Reads a quantity out of the several shapes `value` arrives in — an "HH:MM:SS"
 * clock string, "18.46 days", "7.5 hrs", a bare number, or a number as a string.
 * Returns null only when there is genuinely nothing to multiply.
 */
const parseQty = (v: any): ParsedQty | null => {
    if (v === null || v === undefined || v === '') return null;
    if (typeof v === 'number') return Number.isFinite(v) ? { qty: v, unit: '' } : null;

    const s = String(v).trim();
    if (!s) return null;

    const clock = /^(\d{1,4}):([0-5]?\d)(?::([0-5]?\d))?$/.exec(s);
    if (clock) return { qty: Number(clock[1]) + Number(clock[2]) / 60 + Number(clock[3] || 0) / 3600, unit: 'Hrs' };

    const plain = /^(-?[\d,]*\.?\d+)\s*(days?|d|hrs?|hours?|h)?$/i.exec(s);
    if (!plain) return null;
    const n = Number(plain[1].replace(/,/g, ''));
    if (!Number.isFinite(n)) return null;
    const unit = (plain[2] || '').toLowerCase();
    return { qty: n, unit: unit.startsWith('d') ? 'Days' : unit ? 'Hrs' : '' };
};

/**
 * Line amounts are truncated to paise exactly as `sumBreakdownEarnings` does, so a
 * live SUM() over the lines lands on the very subtotal the app displays.
 */
const trunc2 = (n: number) => Math.trunc(num(n) * 100) / 100;

interface Reconciled {
    qty: number | null;
    rateValue: number | null;
    /** Set when the line's rate IS the master hour/day rate, so its cell can link to it. */
    rateSource: 'hour' | 'day' | null;
}

/**
 * Makes `quantity × rate = amount` hold exactly, which is what lets the amount be a
 * live formula instead of a frozen number.
 *
 * The engine ships the amount to the paisa but the quantity only to the minute
 * ("147:41:00" for 147.6913 h), so multiplying the two back out misses by a few
 * paise. Previously that mismatch made the exporter drop the formula and write a
 * literal — which is exactly why editing a Details cell changed nothing. Instead
 * the quantity is re-derived from the authoritative amount whenever the shipped
 * quantity corroborates it: the rate stays the official contract figure and the
 * quantity silently absorbs the sub-minute residue, invisible at two decimals.
 *
 * When the shipped quantity plainly is not a multiple of the nominal rate — a
 * custom component whose "value" is really an amount, or hours worked but not
 * payable — the line falls back to its own effective rate, or to a flat amount
 * with no rate at all.
 */
function reconcile(amount: number, parsed: ParsedQty | null, nominal: number, isHourly: boolean): Reconciled {
    const flat: Reconciled = { qty: null, rateValue: null, rateSource: null };
    const shipped = parsed ? parsed.qty : null;

    // `value` echoing `earned` means the field carries an amount, not a quantity.
    if (shipped !== null && amount !== 0 && Math.abs(shipped - amount) < 0.005) return flat;

    if (nominal > 0) {
        const derived = amount / nominal;
        const tolerance = shipped === null ? 0 : Math.max(0.02, Math.abs(shipped) * 0.01);
        if (shipped === null || Math.abs(derived - shipped) <= tolerance) {
            return { qty: derived, rateValue: nominal, rateSource: isHourly ? 'hour' : 'day' };
        }
        if (shipped !== 0) {
            const effective = amount / shipped;
            // A zero rate is the honest reading of "worked, but not payable".
            if (effective === 0 || (effective >= nominal / 4 && effective <= nominal * 4)) {
                return { qty: shipped, rateValue: effective, rateSource: null };
            }
        }
    }
    return flat;
}

function amountInWords(n: number): string {
    const value = Math.round(Math.abs(n));
    if (value === 0) return 'Zero Rupees Only';
    const a = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven',
        'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
    const t = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
    const h = (x: number): string => {
        if (!x) return '';
        if (x < 20) return a[x];
        if (x < 100) return t[Math.floor(x / 10)] + (x % 10 ? ' ' + a[x % 10] : '');
        return a[Math.floor(x / 100)] + ' Hundred' + (x % 100 ? ' ' + h(x % 100) : '');
    };
    const parts: string[] = [];
    if (Math.floor(value / 10000000)) parts.push(h(Math.floor(value / 10000000)) + ' Crore');
    if (Math.floor((value % 10000000) / 100000)) parts.push(h(Math.floor((value % 10000000) / 100000)) + ' Lakh');
    if (Math.floor((value % 100000) / 1000)) parts.push(h(Math.floor((value % 100000) / 1000)) + ' Thousand');
    if (value % 1000) parts.push(h(value % 1000));
    return `Rupees ${parts.join(' ')} Only`;
}

// ─── Computed slip model ──────────────────────────────────────────────────────

interface EarningLine {
    name: string;
    /** Display text for the Details column when no numeric quantity applies */
    detailsText: string;
    /** Numeric quantity (hours or days) — enables the amount formula */
    qty: number | null;
    qtyUnit: 'Hrs' | 'Days' | '';
    rateText: string;
    rateValue: number | null;
    rateUnit: 'Hour' | 'Day' | '';
    /** When set, the rate cell links to the master hour/day rate instead of repeating it. */
    rateSource: 'hour' | 'day' | null;
    amount: number;
}

interface DeductionLine {
    name: string;
    detailsText: string;
    qty: number | null;
    /** Unit appended to the quantity, e.g. "late" or "Days" */
    qtyUnit: string;
    /** Quantities that only come in whole units (late check-in counts) */
    integralQty: boolean;
    rateText: string;
    rateValue: number | null;
    /** Unit appended to the rate, e.g. "Day" or "3 late" */
    rateUnit: string;
    /** Slab size for count-based penalties: amount = FLOOR(qty / slab) × rate */
    slab: number | null;
    amount: number;
}

interface StatutoryLine {
    name: string;
    typeLabel: string;
    isPercent: boolean;
    /** Percentage as a fraction (0.12 = 12%) or the fixed rupee rate */
    rateValue: number | null;
    rateText: string;
    base: number | null;
    amount: number;
}

export interface SlipModel {
    companyName: string;
    companyAddress: string;
    companyContact: string;
    companyWebsite: string;
    companyReg: string;
    companyLogo: string | null;
    companyStamp: string | null;

    payMonth: string;
    payPeriod: string;
    payslipId: string;
    generatedOn: string;
    generatedBy: string;

    employeeName: string;
    employeeCode: string;
    designation: string;
    department: string;
    joiningDate: string;
    employmentType: string;
    panNumber: string;
    companyEmail: string;
    bankName: string;
    accountNo: string;
    ifscCode: string;
    paymentStatus: string;

    attendance: { label: string; value: string | number }[];
    rates: { label: string; value: number | string; money: boolean }[];

    variableEarnings: EarningLine[];
    totalVariableEarnings: number;
    fixedEarnings: { name: string; amount: number }[];
    totalFixedEarnings: number;
    totalGrossPay: number;

    variableDeductions: DeductionLine[];
    totalVariableDeductions: number;
    salaryAfterAttendance: number;
    fixedDeductions: StatutoryLine[];
    totalFixedDeductions: number;
    totalDeductions: number;

    netSalary: number;
    /**
     * Gap between the payroll register's own net figure and gross − deductions.
     * Gets its own line once it is large enough to move the printed rupee figure,
     * so the net stays a live formula that still lands on the official number.
     */
    netAdjustment: number;
    netInWords: string;

    salaryHistory: { paidAt: string; payable: number; paid: number; remaining: number }[];
    ledger: {
        date: string; type: string; component: string; method: string; txn: string;
        paid: number; payable: number; remaining: number; status: string; remarks: string;
    }[];
    totalPaid: number;

    summary: { label: string; value: string | number; money: boolean }[];
    fileName: string;
}

export function buildSlipModel(input: SalarySlipExportInput): SlipModel {
    const { employee, apiSalaryData, summaryData, paymentRows = [], month, year, company } = input;
    const rn = input.resolveName ?? ((n: string) => n);
    const rc = input.resolveComponent ?? ((_n: string) => null);

    const rec = apiSalaryData || {};
    const gross = rec.grossPayBreakdown || { variable: {}, fixed: {} };
    const ded = rec.deductionBreakdown || { variable: {}, fixed: {} };
    const co = company || (employee as any)?.companyOverview || null;

    const hourlySalary = num(rec.hourlySalary);
    const dailySalary = hourlySalary ? hourlySalary * 8 : num(rec.employeeCardDetails?.dailySalary);

    const sortedEntries = (entries: [string, any][]) =>
        [...entries].sort(([a], [b]) => (rc(a)?.sortOrder ?? 999) - (rc(b)?.sortOrder ?? 999));

    // Same visibility rule as the Financial Breakdown screen.
    const isVisible = ([key, item]: [string, any]) => {
        const meta = rc(item?.name || key);
        return meta === null || meta.isActive !== false;
    };

    // ── Earnings ──────────────────────────────────────────────────────────────
    const variableEarnings: EarningLine[] = sortedEntries(Object.entries(gross.variable || {}))
        .filter(isVisible)
        .map(([key, item]: [string, any], index): EarningLine => {
            const meta = rc(item.name || key);
            const masterCalc = meta?.calculationType?.toUpperCase();
            const parsed = parseQty(item.value);

            // The engine's own unit wins: under "days" display mode even working time
            // arrives as days and must be priced at the daily rate, not the hourly one.
            const isHourly = parsed?.unit === 'Days' ? false
                : parsed?.unit === 'Hrs' ? true
                    : masterCalc === 'DAILY' ? false
                        : masterCalc === 'HOURLY' ? true
                            : index < 2;

            const amount = trunc2(item.earned);
            const { qty, rateValue, rateSource } = reconcile(amount, parsed, isHourly ? hourlySalary : dailySalary, isHourly);

            return {
                name: rn(item.name || key),
                detailsText: formatValue(item.value, item.type),
                qty,
                qtyUnit: qty === null ? '' : isHourly ? 'Hrs' : 'Days',
                rateText: rateValue === null ? '—' : `${money2(rateValue)} / ${isHourly ? 'Hour' : 'Day'}`,
                rateValue,
                rateUnit: rateValue === null ? '' : isHourly ? 'Hour' : 'Day',
                rateSource,
                amount,
            };
        });

    const fixedEarnings = sortedEntries(Object.entries(gross.fixed || {}))
        .filter(isVisible)
        .map(([key, item]: [string, any]) => ({ name: rn(item.name || key), amount: trunc2(item.earned) }));

    // Subtotals are the sum of the lines actually printed, using the same per-line
    // truncation as `sumBreakdownEarnings`, so the panel adds up on the page and a
    // live SUM() lands exactly on it. Where a hidden component carries earnings the
    // difference against the register surfaces on the reconciliation line below.
    const totalVariableEarnings = variableEarnings.reduce((acc, e) => acc + e.amount, 0);
    const totalFixedEarnings = fixedEarnings.reduce((acc, e) => acc + e.amount, 0);
    const totalGrossPay = totalVariableEarnings + totalFixedEarnings;

    // ── Deductions ────────────────────────────────────────────────────────────
    const variableDeductionEntries = sortedEntries(Object.entries(ded.variable || {}))
        .filter(([key, item]: [string, any]) => item?.isActive !== false && isVisible([key, item]));

    const fixedDeductionEntries = sortedEntries(Object.entries(ded.fixed || {}))
        .filter(([key, item]: [string, any]) => {
            const meta = rc(item?.name || key);
            if (meta !== null && meta.isActive === false) return false;
            if (item?.isActive !== false) return true;
            return num(item?.earned) > 0 || num(item?.extraAmount) > 0;
        });

    const effectiveEarned = (item: any): number => {
        const earned = Math.max(0, num(item?.earned));
        if (earned > 0) return earned;
        if (item?.isActive === false) return Math.max(0, num(item?.extraAmount));
        return 0;
    };

    const totalVariableDeductions = variableDeductionEntries.reduce((acc, [, item]: [string, any]) => acc + num(item?.earned), 0);
    const totalFixedDeductions = fixedDeductionEntries.reduce((acc, [, item]: [string, any]) => acc + Math.round(effectiveEarned(item)), 0);
    const salaryAfterAttendance = Math.max(0, totalGrossPay - totalVariableDeductions);
    const totalDeductions = totalVariableDeductions + totalFixedDeductions;

    const variableDeductions: DeductionLine[] = variableDeductionEntries.map(([key, item]: [string, any]): DeductionLine => {
        const name = item?.name || key;
        const isLate = /late\s*check/i.test(key) || /late\s*attendance/i.test(key)
            || /late\s*check/i.test(name) || /late\s*attendance/i.test(name);
        const amount = num(item?.earned);
        const parsed = parseQty(item?.value);

        if (isLate) {
            // A late-check-in penalty is slab-based: one charge of `rateAmount` per
            // `countLimit` lates. Both come from the engine; when an older payload
            // omits the limit it is recovered from the charge already applied.
            const percent = num(item?.ratePercent ?? item?.configuredValue ?? item?.deductionPercent);
            const slabAmount = num(item?.rateAmount) || (dailySalary && percent ? dailySalary * (percent / 100) : 0);
            const count = parsed ? parsed.qty : null;

            let slab = num(item?.countLimit ?? item?.meta?.countLimit);
            if (!(slab > 0) && slabAmount > 0 && amount > 0 && count) {
                const slabs = Math.round(amount / slabAmount);
                const guess = slabs > 0 ? count / slabs : 0;
                if (guess > 0 && Math.abs(guess - Math.round(guess)) < 0.001) slab = Math.round(guess);
            }

            if (slabAmount > 0 && slab > 0 && count !== null) {
                return {
                    name: rn(name),
                    detailsText: safe(item?.value),
                    qty: count,
                    qtyUnit: 'late',
                    integralQty: true,
                    rateText: `${money2(slabAmount)} / ${slab} late`,
                    rateValue: slabAmount,
                    rateUnit: `${slab} late`,
                    slab,
                    amount,
                };
            }
        }

        const { qty, rateValue } = reconcile(amount, parsed, dailySalary, false);
        const explicitRate = item?.rateDisplay || item?.rateLabel;

        return {
            name: rn(name),
            detailsText: safe(item?.value),
            qty,
            qtyUnit: qty === null ? '' : 'Days',
            integralQty: false,
            rateText: rateValue !== null ? `${money2(rateValue)} / Day` : (explicitRate ? String(explicitRate) : '—'),
            rateValue,
            rateUnit: rateValue !== null ? 'Day' : '',
            slab: null,
            amount,
        };
    });

    const fixedDeductions: StatutoryLine[] = fixedDeductionEntries.map(([key, item]: [string, any]) => {
        const isPercent = String(item.type).toLowerCase() === 'percentage';
        const inactiveWithExtra = item?.isActive === false;
        const resolved = rn(item.name || key);
        const displayName = resolved === 'Professional Fees' ? 'Tax Deducted at Source (TDS)' : resolved;
        const isTds = displayName.includes('Tax Deducted at Source');

        return {
            name: inactiveWithExtra ? `${displayName} (Manual Extra)` : displayName,
            typeLabel: isPercent ? 'Percentage' : 'Fixed',
            isPercent,
            rateValue: inactiveWithExtra ? null : isPercent ? num(item.value) / 100 : num(item.value),
            rateText: inactiveWithExtra ? '—' : isPercent ? `${item.value}%` : money2(num(item.value)),
            base: (isPercent || isTds) ? salaryAfterAttendance : null,
            amount: Math.round(effectiveEarned(item)),
        };
    });

    const recordNet = num(rec.netAmountInNumber ?? summaryData?.netSalary);
    const derivedNet = totalGrossPay - totalDeductions;
    const netSalary = recordNet || derivedNet;

    // ── Period / identity ─────────────────────────────────────────────────────
    const start = dayjs(new Date(year, month - 1, 1));
    const end = start.endOf('month');
    const employeeName = `${employee?.users?.firstName || ''} ${employee?.users?.lastName || ''}`.replace(/\s+/g, ' ').trim() || '—';
    const employeeCode = safe(employee?.employeeCode, '');
    const bank = (employee as any)?.EmployeeBankDetails?.[0] || (employee as any)?.employeeBankDetails?.[0] || null;

    // ── Attendance & rates ────────────────────────────────────────────────────
    // Day and check-in counts go in as real numbers so the sheet can compute with
    // them; the HH:MM:SS clock readings stay as text, they are read, not multiplied.
    const attendance: { label: string; value: string | number }[] = [
        { label: 'Total Working Days', value: numOrDash(rec.workingdays) },
        { label: 'Present Days', value: numOrDash(rec.presentDays) },
        { label: 'Absent Days', value: numOrDash(rec.absentDays) },
        { label: 'Paid Leaves', value: numOrDash(rec.leavesDays) },
        { label: 'Unpaid Leaves', value: numOrDash(rec.unpaidLeaveDays) },
        { label: 'Total Payable Days', value: numOrDash(rec.totalPayableDays) },
        { label: 'Late Check-ins', value: numOrDash(rec.lateCheckinDays) },
        { label: 'Extra Days Worked', value: numOrDash(rec.extraDaysWorked) },
        { label: 'Expected Working Hours', value: safe(rec.workingHours) },
        { label: 'Payable Hours', value: safe(rec.payableHours) },
        { label: 'Overtime', value: safe(rec.overTime) },
        { label: 'Remaining Time', value: safe(rec.remainingTime) },
    ];

    const rates: { label: string; value: number | string; money: boolean }[] = [
        { label: 'Annual CTC', value: rec.annualCTC ? num(rec.annualCTC) : '—', money: !!rec.annualCTC },
        { label: 'Monthly Basic Salary', value: rec.basicSalaryInNumber ? num(rec.basicSalaryInNumber) : '—', money: !!rec.basicSalaryInNumber },
        { label: 'Per Day Rate', value: dailySalary || '—', money: !!dailySalary },
        { label: 'Per Hour Rate', value: hourlySalary || '—', money: !!hourlySalary },
    ];

    // ── Payments ──────────────────────────────────────────────────────────────
    const salaryPayments = (rec.paymentHistory || [])
        .filter((p: any) => String(p?.type || 'SALARY').toUpperCase() !== 'GOVERNMENT')
        .slice()
        .sort((a: any, b: any) => new Date(a.paymentDate || 0).getTime() - new Date(b.paymentDate || 0).getTime());

    let cumulative = 0;
    const salaryHistory = salaryPayments.map((p: any) => {
        const paid = num(p.amount);
        cumulative += paid;
        return {
            paidAt: fmtDate(p.paymentDate || p.createdAt, true),
            payable: netSalary,
            paid,
            remaining: Math.max(0, netSalary - cumulative),
        };
    });

    const ledger = paymentRows.map((row: any) => ({
        date: fmtDate(row.displayDate, true),
        type: row.paymentType === 'GOVERNMENT' ? 'Government' : 'Salary',
        component: safe(row.deductionType),
        method: safe(row.paymentMethod),
        txn: safe(row.transactionId),
        paid: num(row.calculatedPaidAmount),
        payable: num(row.calculatedNetSalary),
        remaining: num(row.calculatedRemainingAmount),
        status: safe(row.calculatedStatus),
        remarks: safe(row.remarks),
    }));
    const totalPaid = ledger.reduce((acc, r) => acc + r.paid, 0);

    const s = summaryData || {};
    const summary: { label: string; value: string | number; money: boolean }[] = [
        { label: 'Net Salary Payable', value: netSalary, money: true },
        { label: 'Salary Paid', value: num(s.salaryPaid), money: true },
        { label: 'Salary Pending', value: num(s.salaryPending), money: true },
        { label: 'Government Deductions', value: num(s.totalGovtDeduction), money: true },
        { label: 'Government Paid', value: num(s.governmentPaid), money: true },
        { label: 'Government Pending', value: num(s.governmentPending), money: true },
    ];
    if (s.hasRetention) {
        summary.push(
            { label: 'Retention Deducted', value: num(s.totalRetention), money: true },
            { label: 'Retention Paid', value: num(s.retentionPaid), money: true },
            { label: 'Retention Pending', value: num(s.retentionPending), money: true },
        );
    }
    summary.push({ label: 'Total Company Payout', value: num(s.totalCompanyPayout), money: true });

    const companyName = safe(co?.name, 'Company');
    const safeFile = employeeName.replace(/[^\w]+/g, '_').replace(/^_|_$/g, '') || 'Employee';
    // Skip whatever the company profile does not carry, so the header never shows
    // orphan separators or em-dashes.
    const joinParts = (parts: any[], sep: string) => parts.map(p => safe(p, '')).filter(Boolean).join(sep);

    return {
        companyName,
        // Branch office address takes priority, exactly like the PDF slip.
        companyAddress: safe((employee as any)?.branches?.address || co?.address),
        companyContact: joinParts([co?.superAdminEmail, co?.contactNumber], '   ·   '),
        companyWebsite: safe(co?.websiteUrl, ''),
        companyReg: joinParts(
            [co?.panNo ? `CIN: ${co.panNo}` : '', co?.gstNumber ? `GSTIN: ${co.gstNumber}` : ''],
            '   |   ',
        ),
        companyLogo: co?.logo || null,
        companyStamp: co?.salaryStamp || null,

        payMonth: start.format('MMMM YYYY'),
        payPeriod: `${start.format('D MMM')} - ${end.format('D MMM')}`,
        payslipId: `PS-${year}-${String(month).padStart(2, '0')}-${employeeCode || '0000'}`,
        generatedOn: dayjs().format('DD MMM YYYY, hh:mm A'),
        generatedBy: safe(input.generatedBy, 'Payroll System'),

        employeeName,
        employeeCode: employeeCode || '—',
        designation: safe(employee?.designations?.role),
        department: safe(employee?.departments?.name),
        joiningDate: employee?.dateOfJoining ? fmtDate(employee.dateOfJoining) : '—',
        employmentType: safe((employee as any)?.employeeTypeConfig?.name || (employee as any)?.companyEmployeeTypes?.type || employee?.employeeType, 'Full Time'),
        panNumber: safe((employee as any)?.panNumber),
        companyEmail: safe(employee?.companyEmailId),
        bankName: safe(bank?.bankName),
        accountNo: maskAcct(bank?.accountNumber),
        ifscCode: safe(bank?.ifscCode),
        paymentStatus: safe(rec.status),

        attendance,
        rates,

        variableEarnings,
        totalVariableEarnings,
        fixedEarnings,
        totalFixedEarnings,
        totalGrossPay,

        variableDeductions,
        totalVariableDeductions,
        salaryAfterAttendance,
        fixedDeductions,
        totalFixedDeductions,
        totalDeductions,

        netSalary,
        // Kept at full precision, never truncated: this is the term that has to make
        // the live net land exactly on the register's figure.
        netAdjustment: netSalary - derivedNet,
        netInWords: amountInWords(netSalary),

        salaryHistory,
        ledger,
        totalPaid,

        summary,
        fileName: `Salary_Slip_${safeFile}_${start.format('MMM_YYYY')}`,
    };
}

// ─── Excel styling constants ──────────────────────────────────────────────────

const argb = (hex: string) => 'FF' + hex.replace('#', '').toUpperCase();

// Indian digit grouping (₹12,34,567.89). The final section also catches negatives.
const INR2 = '[>=10000000]"₹"##\\,##\\,##\\,##0.00;[>=100000]"₹"##\\,##\\,##0.00;"₹"#,##0.00';
const INR0 = '[>=10000000]"₹"##\\,##\\,##\\,##0;[>=100000]"₹"##\\,##\\,##0;"₹"#,##0';
// Deductions are held as positive numbers and worn with a minus. The leading
// `[<0.005]` section keeps a nil deduction reading "₹0" rather than "-₹0", and the
// two-digit grouping repeats leftwards on its own, so crores still come out right.
const INR2_NEG = '[<0.005]"₹"#,##0.00;[>=100000]"-₹"##\\,##\\,##0.00;"-₹"#,##0.00';
const INR0_NEG = '[<0.005]"₹"#,##0;[>=100000]"-₹"##\\,##\\,##0;"-₹"#,##0';
/** Signed format for a figure that may legitimately fall either side of zero. */
const INR2_SIGNED = '"₹"#,##0.00;"-₹"#,##0.00;"₹"0.00';

const colLetter = (col: number) => String.fromCharCode(64 + col);

/** Quantity format. Whole-unit counts drop the decimals — `0.##` would render "4." */
const qtyFmt = (unit: string, integral = false) => `${integral ? '0' : '0.00'}${unit ? `" ${unit}"` : ''}`;

/** Rate format carrying its own unit, e.g. ₹80.65 / Hour or ₹322.58 / 3 late. */
const rateFmt = (unit: string) => `"₹"#,##0.00${unit ? `" / ${unit}"` : ''}`;

const C = {
    navy: '#0f2044',
    navyLight: '#1e3a5f',
    slate: '#334155',
    slateSoft: '#e2e8f0',
    muted: '#64748b',
    ink: '#0f172a',
    white: '#ffffff',
    greenBg: '#f0fdf4', greenInk: '#166534', greenLine: '#bbf7d0',
    redBg: '#fef2f2', redInk: '#b91c1c', redLine: '#fecaca',
    blueBg: '#eff6ff', blueInk: '#1d4ed8', blueLine: '#bfdbfe',
    amberBg: '#fffbeb', amberInk: '#92400e',
    grey: '#f8fafc',
};

const thin = (hex: string) => ({ style: 'thin' as const, color: { argb: argb(hex) } });
const boxBorder = (hex: string) => ({ top: thin(hex), left: thin(hex), bottom: thin(hex), right: thin(hex) });

// Sheet grid: A spacer | B-E earnings | F gap | G-K deductions
const COL = { first: 2, earnDesc: 2, earnDetails: 3, earnRate: 4, earnAmt: 5, gap: 6, dedDesc: 7, dedType: 8, dedRate: 9, dedBase: 10, dedAmt: 11, last: 11 };

interface CellStyle {
    bold?: boolean;
    size?: number;
    color?: string;
    bg?: string;
    align?: 'left' | 'center' | 'right';
    valign?: 'top' | 'middle' | 'bottom';
    italic?: boolean;
    border?: string;
    /** Draw only a top rule — used for the signature line */
    borderTop?: string;
    indent?: number;
    wrap?: boolean;
}

function applyStyle(cell: any, st: CellStyle) {
    cell.font = {
        name: 'Calibri',
        size: st.size ?? 10,
        bold: !!st.bold,
        italic: !!st.italic,
        color: { argb: argb(st.color ?? C.ink) },
    };
    if (st.bg) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: argb(st.bg) } };
    cell.alignment = {
        horizontal: st.align ?? 'left',
        vertical: st.valign ?? 'middle',
        indent: st.indent ?? (st.align === 'left' ? 1 : 0),
        wrapText: !!st.wrap,
    };
    if (st.border) cell.border = boxBorder(st.border);
    else if (st.borderTop) cell.border = { top: { style: 'medium' as const, color: { argb: argb(st.borderTop) } } };
}

/** Merge c1..c2 on `row`, write `value`, and style every cell of the range. */
function band(ws: any, row: number, c1: number, c2: number, value: any, st: CellStyle) {
    if (c2 > c1) ws.mergeCells(row, c1, row, c2);
    const cell = ws.getCell(row, c1);
    cell.value = value;
    for (let c = c1; c <= c2; c++) applyStyle(ws.getCell(row, c), st);
    return cell;
}

/** Merge a rectangle, write `value` into it, and style every cell of the range. */
function block(ws: any, r1: number, c1: number, r2: number, c2: number, value: any, st: CellStyle) {
    if (r2 > r1 || c2 > c1) ws.mergeCells(r1, c1, r2, c2);
    const cell = ws.getCell(r1, c1);
    cell.value = value;
    for (let row = r1; row <= r2; row++) {
        for (let col = c1; col <= c2; col++) applyStyle(ws.getCell(row, col), st);
    }
    return cell;
}

/** Writes a formula only when it reproduces the payroll engine's figure. */
function amountCell(ws: any, row: number, col: number, expected: number, formula: string | null, computed: number | null, st: CellStyle, numFmt: string) {
    const cell = ws.getCell(row, col);
    const usable = formula !== null && computed !== null && Math.abs(computed - expected) < 0.51;
    cell.value = usable ? ({ formula, result: expected } as any) : expected;
    cell.numFmt = numFmt;
    applyStyle(cell, st);
    return cell;
}

interface LoadedImage {
    id: number;
    /** Intrinsic pixel size — used to place the image without distorting it */
    natural: { w: number; h: number } | null;
}

async function tryAddImage(wb: any, src: string | null): Promise<LoadedImage | null> {
    if (!src) return null;
    try {
        const extension = /\.jpe?g(\?|$)/i.test(src) ? 'jpeg' : /\.gif(\?|$)/i.test(src) ? 'gif' : 'png';

        let blob: Blob;
        let id: number;
        if (src.startsWith('data:')) {
            id = wb.addImage({ base64: src, extension });
            blob = await (await fetch(src)).blob();
        } else {
            const res = await fetch(src, { mode: 'cors' });
            if (!res.ok) return null;
            blob = await res.blob();
            id = wb.addImage({ buffer: await blob.arrayBuffer(), extension } as any);
        }

        let natural: { w: number; h: number } | null = null;
        try {
            if (typeof createImageBitmap === 'function') {
                const bmp = await createImageBitmap(blob);
                natural = { w: bmp.width, h: bmp.height };
                bmp.close?.();
            }
        } catch { /* intrinsic size is an optimisation, not a requirement */ }

        return { id, natural };
    } catch {
        return null; // branding image is decorative — never fail the export for it
    }
}

// ── Geometry: Excel column widths are in characters, row heights in points,
//    while image anchors/extents are in pixels. These convert between them so a
//    logo can be centred in its plate at its true aspect ratio.
const colWidthPx = (ws: any, col: number) => Math.round((ws.getColumn(col).width ?? 8.43) * 7 + 5);
const rowHeightPx = (ws: any, row: number) => (ws.getRow(row).height ?? 15) * (4 / 3);

const EMU_PER_PX = 9525;

/**
 * Native cell+EMU anchor for an offset measured from the top-left of (startRow, startCol).
 *
 * ExcelJS's fractional `{col, row}` anchor form multiplies the fraction by
 * `columnWidth * 10000`, which is not EMU — offsets come out roughly seven times
 * too small and every image ends up hugging the left edge of its cell. Supplying
 * nativeCol/nativeColOff directly bypasses that conversion.
 */
function nativeAnchor(ws: any, startRow: number, startCol: number, xPx: number, yPx: number) {
    let col = startCol;
    let left = Math.max(0, xPx);
    for (let guard = 0; guard < 64; guard++) {
        const w = colWidthPx(ws, col);
        if (left < w || w <= 0) break;
        left -= w;
        col++;
    }

    let row = startRow;
    let top = Math.max(0, yPx);
    for (let guard = 0; guard < 64; guard++) {
        const h = rowHeightPx(ws, row);
        if (top < h || h <= 0) break;
        top -= h;
        row++;
    }

    return {
        nativeCol: col - 1,
        nativeColOff: Math.round(left * EMU_PER_PX),
        nativeRow: row - 1,
        nativeRowOff: Math.round(top * EMU_PER_PX),
    };
}

/** Scale to fit inside the box without distorting the image. */
function fitImage(natural: { w: number; h: number } | null, maxW: number, maxH: number, fallbackRatio: number) {
    const w0 = natural?.w || 100 * fallbackRatio;
    const h0 = natural?.h || 100;
    const scale = Math.min(maxW / w0, maxH / h0);
    return { width: Math.round(w0 * scale), height: Math.round(h0 * scale) };
}

/**
 * Places an image centred inside a merged cell plate, preserving its aspect ratio.
 * `rows`/`cols` are the 1-based bounds of the plate.
 */
function placeImageInPlate(
    ws: any, img: LoadedImage,
    r1: number, c1: number, r2: number, c2: number,
    padX: number, padY: number, fallbackRatio: number,
    capW = Infinity, capH = Infinity,
) {
    let plateW = 0;
    for (let c = c1; c <= c2; c++) plateW += colWidthPx(ws, c);
    let plateH = 0;
    for (let row = r1; row <= r2; row++) plateH += rowHeightPx(ws, row);

    const { width, height } = fitImage(
        img.natural,
        Math.min(plateW - padX * 2, capW),
        Math.min(plateH - padY * 2, capH),
        fallbackRatio,
    );

    ws.addImage(img.id, {
        tl: nativeAnchor(ws, r1, c1, Math.max(0, (plateW - width) / 2), Math.max(0, (plateH - height) / 2)),
        ext: { width, height },
        editAs: 'oneCell',
    });
}

// ─── Excel (.xlsx) ────────────────────────────────────────────────────────────

export async function downloadSalarySlipXlsx(input: SalarySlipExportInput): Promise<void> {
    const m = buildSlipModel(input);

    const ExcelJS: any = await import('exceljs');
    const Workbook = ExcelJS.Workbook ?? ExcelJS.default?.Workbook;
    const wb = new Workbook();
    wb.creator = m.companyName;
    wb.created = new Date();
    // Excel recalculates every formula when the file is opened, so the sheet is live
    // even where a cached result was not written.
    wb.calcProperties.fullCalcOnLoad = true;

    const ws = wb.addWorksheet('Salary Slip', {
        views: [{ showGridLines: false }],
        pageSetup: { paperSize: 9, orientation: 'portrait', fitToPage: true, fitToWidth: 1, fitToHeight: 0, margins: { left: 0.3, right: 0.3, top: 0.4, bottom: 0.4, header: 0.2, footer: 0.2 } },
    });

    ws.columns = [
        { width: 2 },   // A spacer
        { width: 30 },  // B earnings description
        { width: 15 },  // C details
        { width: 18 },  // D rate
        { width: 16 },  // E amount
        { width: 2 },   // F gap
        { width: 26 },  // G deduction description
        { width: 13 },  // H type / details
        { width: 14 },  // I rate
        { width: 14 },  // J base
        { width: 16 },  // K amount
    ];

    let r = 1;

    // ── HEADER — logo left | title centre | company details right, as on the PDF ──
    ws.getRow(r).height = 7;
    band(ws, r, COL.first, COL.last, '', { bg: C.navy });
    r++;

    const logo = await tryAddImage(wb, m.companyLogo);
    const hTop = r;
    const hRows = 5;
    const headerBg: CellStyle = { bg: C.white };

    // Left — logo plate
    block(ws, hTop, 2, hTop + hRows - 1, 3, '', { ...headerBg, align: 'center' });

    // Centre — statement title
    block(ws, hTop, 4, hTop, 8, 'MONTHLY PAYROLL STATEMENT', { bold: true, size: 8, color: C.muted, align: 'center', bg: C.white });
    block(ws, hTop + 1, 4, hTop + 2, 8, 'SALARY SLIP', { bold: true, size: 20, color: C.navy, align: 'center', bg: C.white });
    block(ws, hTop + 3, 4, hTop + 4, 8, m.companyName, { bold: true, size: 11, color: C.blueInk, align: 'center', bg: C.white, valign: 'top' });

    // Right — registered details. The address gets three rows: branch addresses are
    // long and a merged cell clips instead of growing.
    block(ws, hTop, 9, hTop + 2, 11, m.companyAddress, { size: 7.5, color: C.muted, align: 'right', bg: C.white, wrap: true, valign: 'top' });
    block(ws, hTop + 3, 9, hTop + 3, 11,
        [m.companyContact, m.companyWebsite].filter(Boolean).join('   ·   '),
        { size: 8, color: C.muted, align: 'right', bg: C.white });
    block(ws, hTop + 4, 9, hTop + 4, 11, m.companyReg, { size: 7.5, color: C.muted, align: 'right', bg: C.white });

    [17, 17, 15, 14, 14].forEach((h, i) => { ws.getRow(hTop + i).height = h; });
    r = hTop + hRows;

    // Logo: centred in the B:C plate at its own aspect ratio (never stretched).
    if (logo) placeImageInPlate(ws, logo, hTop, 2, hTop + hRows - 1, 3, 14, 8, 2.4, 170, 58);

    // Rule under the header
    band(ws, r, COL.first, COL.last, '', { bg: C.blueInk });
    ws.getRow(r).height = 3;
    r++;
    ws.getRow(r).height = 6;
    r++;

    // ── PAY PERIOD BAR ────────────────────────────────────────────────────────
    const payBarStyle: CellStyle = { bold: true, size: 8, color: '#c7d2fe', align: 'center', bg: C.navy };
    const payValStyle: CellStyle = { bold: true, size: 11, color: C.white, align: 'center', bg: C.navy };
    band(ws, r, 2, 3, 'PAY MONTH', payBarStyle);
    band(ws, r, 4, 5, 'PAY PERIOD', payBarStyle);
    band(ws, r, 6, 8, 'PAYSLIP ID', payBarStyle);
    band(ws, r, 9, 11, 'GENERATED ON', payBarStyle);
    ws.getRow(r).height = 14;
    r++;
    band(ws, r, 2, 3, m.payMonth, payValStyle);
    band(ws, r, 4, 5, m.payPeriod, payValStyle);
    band(ws, r, 6, 8, m.payslipId, payValStyle);
    band(ws, r, 9, 11, m.generatedOn, payValStyle);
    ws.getRow(r).height = 18;
    r += 2;

    // ── EMPLOYEE DETAILS ──────────────────────────────────────────────────────
    band(ws, r, COL.first, COL.last, 'EMPLOYEE DETAILS', { bold: true, size: 11, color: C.white, bg: C.navyLight });
    ws.getRow(r).height = 20;
    r++;

    const infoPairs: [string, any][] = [
        ['Employee Name', m.employeeName], ['Employee Code', m.employeeCode],
        ['Designation', m.designation], ['Department', m.department],
        ['Joining Date', m.joiningDate], ['Employment Type', m.employmentType],
        ['PAN Number', m.panNumber], ['Company Email', m.companyEmail],
        ['Bank Name', m.bankName], ['A/C No (Last 4)', m.accountNo],
        ['IFSC Code', m.ifscCode], ['Payment Status', m.paymentStatus],
    ];
    const lblStyle: CellStyle = { bold: true, size: 9, color: C.muted, bg: C.grey, border: C.slateSoft };
    const valStyle: CellStyle = { bold: true, size: 10, color: C.ink, bg: C.white, border: C.slateSoft };

    for (let i = 0; i < infoPairs.length; i += 2) {
        band(ws, r, 2, 2, infoPairs[i][0], lblStyle);
        band(ws, r, 3, 5, infoPairs[i][1], valStyle);
        if (infoPairs[i + 1]) {
            band(ws, r, 7, 8, infoPairs[i + 1][0], lblStyle);
            band(ws, r, 9, 11, infoPairs[i + 1][1], valStyle);
        } else {
            band(ws, r, 7, 11, '', valStyle);
        }
        ws.getRow(r).height = 16;
        r++;
    }
    r++;

    // ── ATTENDANCE & RATES ────────────────────────────────────────────────────
    band(ws, r, COL.first, COL.last, 'ATTENDANCE, TIME & SALARY RATES', { bold: true, size: 11, color: C.white, bg: C.navyLight });
    ws.getRow(r).height = 20;
    r++;

    const attPairs = [...m.attendance.map(a => ({ label: a.label, value: a.value, money: false })), ...m.rates];

    /** Absolute reference of every numeric cell here, so later rows can point at it. */
    const ref: Record<string, { addr: string; row: number; col: number; value: number }> = {};

    for (let i = 0; i < attPairs.length; i += 2) {
        ([[attPairs[i], 2, 3, 5], [attPairs[i + 1], 7, 9, 11]] as const).forEach(([item, lblCol, valCol, valEnd]) => {
            if (!item) {
                band(ws, r, lblCol, valEnd, '', valStyle);
                return;
            }
            band(ws, r, lblCol, valCol - 1, item.label, lblStyle);
            const cell = band(ws, r, valCol, valEnd, item.value, valStyle);
            if (typeof item.value === 'number') {
                if (item.money) cell.numFmt = INR2;
                ref[item.label] = { addr: `$${colLetter(valCol)}$${r}`, row: r, col: valCol, value: item.value };
            }
        });
        ws.getRow(r).height = 16;
        r++;
    }

    /**
     * Turns a literal into a formula, but only when the formula reproduces the value
     * the payroll engine already put there. A mismatch means the identity being
     * assumed does not hold for this company's configuration, so the number stands.
     */
    const relink = (label: string, formula: string, computed: number, fmt?: string): boolean => {
        const target = ref[label];
        if (!target || !Number.isFinite(computed) || Math.abs(computed - target.value) >= 0.005) return false;
        const cell = ws.getCell(target.row, target.col);
        cell.value = { formula, result: target.value } as any;
        if (fmt) cell.numFmt = fmt;
        return true;
    };

    const hourRateRef = ref['Per Hour Rate']?.addr ?? null;
    const dayRateRef = ref['Per Day Rate']?.addr ?? null;

    // Make the rate block itself compute: the per-day rate is the per-hour rate over a
    // standard working day, and the monthly basic is a twelfth of the annual CTC. Change
    // the hourly rate and every day-priced line downstream follows.
    if (hourRateRef && ref['Per Day Rate']) {
        relink('Per Day Rate', `${hourRateRef}*8`, ref['Per Hour Rate'].value * 8, INR2);
    }
    if (ref['Annual CTC'] && ref['Monthly Basic Salary']) {
        relink('Monthly Basic Salary', `${ref['Annual CTC'].addr}/12`, ref['Annual CTC'].value / 12, INR2);
    }
    // Payable days: try the fuller identity first, fall back to the plain one. relink
    // writes nothing where neither reproduces the engine's figure, so a company whose
    // configuration counts days differently simply keeps its literal.
    if (ref['Present Days'] && ref['Paid Leaves']) {
        const present = ref['Present Days'];
        const leaves = ref['Paid Leaves'];
        const extra = ref['Extra Days Worked'];
        const withExtra = extra
            ? relink('Total Payable Days', `${present.addr}+${leaves.addr}+${extra.addr}`, present.value + leaves.value + extra.value)
            : false;
        if (!withExtra) {
            relink('Total Payable Days', `${present.addr}+${leaves.addr}`, present.value + leaves.value);
        }
    }
    r++;

    // ── SUMMARY CARDS (filled in later, once the total cells exist) ────────────
    band(ws, r, 2, 3, 'GROSS PAY', { bold: true, size: 8, color: C.greenInk, align: 'center', bg: C.greenBg, border: C.greenLine });
    band(ws, r, 4, 5, 'ATTENDANCE ADJ.', { bold: true, size: 8, color: C.amberInk, align: 'center', bg: C.amberBg, border: '#fde68a' });
    band(ws, r, 6, 8, 'TOTAL DEDUCTIONS', { bold: true, size: 8, color: C.redInk, align: 'center', bg: C.redBg, border: C.redLine });
    band(ws, r, 9, 11, 'NET PAYABLE', { bold: true, size: 8, color: C.blueInk, align: 'center', bg: C.blueBg, border: C.blueLine });
    ws.getRow(r).height = 14;
    r++;
    const cardRow = r;
    band(ws, r, 2, 3, 0, { bold: true, size: 13, color: C.greenInk, align: 'center', bg: C.greenBg, border: C.greenLine });
    band(ws, r, 4, 5, 0, { bold: true, size: 13, color: C.amberInk, align: 'center', bg: C.amberBg, border: '#fde68a' });
    band(ws, r, 6, 8, 0, { bold: true, size: 13, color: C.redInk, align: 'center', bg: C.redBg, border: C.redLine });
    band(ws, r, 9, 11, 0, { bold: true, size: 13, color: C.blueInk, align: 'center', bg: C.blueBg, border: C.blueLine });
    ws.getRow(r).height = 24;
    r += 2;

    // ── BREAKDOWN PANEL HEADERS ───────────────────────────────────────────────
    band(ws, r, 2, 5, 'EARNINGS BREAKDOWN', { bold: true, size: 11, color: C.greenInk, bg: C.greenBg, border: C.greenLine });
    band(ws, r, 7, 11, 'DEDUCTIONS BREAKDOWN', { bold: true, size: 11, color: C.redInk, bg: C.redBg, border: C.redLine });
    ws.getRow(r).height = 20;
    r++;

    // Section labels: A | 1
    band(ws, r, 2, 5, 'A. Variable Earnings (Work-Based)', { bold: true, size: 9, color: C.greenInk, bg: C.greenBg });
    band(ws, r, 7, 11, '1. Attendance Adjustments', { bold: true, size: 9, color: C.redInk, bg: C.redBg });
    ws.getRow(r).height = 16;
    r++;

    // Table headers
    const thStyle: CellStyle = { bold: true, size: 8, color: C.muted, bg: C.slateSoft, border: '#cbd5e1' };
    band(ws, r, 2, 2, 'DESCRIPTION', thStyle);
    band(ws, r, 3, 3, 'DETAILS', { ...thStyle, align: 'center' });
    band(ws, r, 4, 4, 'RATE', { ...thStyle, align: 'center' });
    band(ws, r, 5, 5, 'AMOUNT (₹)', { ...thStyle, align: 'right' });
    band(ws, r, 7, 7, 'DESCRIPTION', thStyle);
    band(ws, r, 8, 8, 'DETAILS', { ...thStyle, align: 'center' });
    band(ws, r, 9, 9, 'RATE', { ...thStyle, align: 'center' });
    band(ws, r, 10, 10, '', thStyle);
    band(ws, r, 11, 11, 'AMOUNT (₹)', { ...thStyle, align: 'right' });
    ws.getRow(r).height = 15;
    r++;

    // Section A + section 1 rows, written side by side like the PDF grid
    const rowStyle: CellStyle = { size: 10, color: C.ink, bg: C.white, border: C.slateSoft };
    const rowCenter: CellStyle = { ...rowStyle, align: 'center' };
    const earnAmtStyle: CellStyle = { ...rowStyle, align: 'right', bold: true };
    const dedAmtStyle: CellStyle = { ...rowStyle, align: 'right', bold: true, color: C.redInk };

    const varEarnStart = r;
    const varDedStart = r;
    const parallelRows = Math.max(m.variableEarnings.length, m.variableDeductions.length, 1);

    for (let i = 0; i < parallelRows; i++) {
        const e = m.variableEarnings[i];
        const d = m.variableDeductions[i];

        if (e) {
            band(ws, r, 2, 2, e.name, rowStyle);
            const detail = ws.getCell(r, 3);
            if (e.qty !== null) {
                detail.value = e.qty;
                detail.numFmt = qtyFmt(e.qtyUnit);
            } else {
                detail.value = e.detailsText;
            }
            applyStyle(detail, rowCenter);

            const rate = ws.getCell(r, 4);
            if (e.rateValue !== null) {
                // Lines priced at the standard rate point back at the rate block, so one
                // edit there re-prices the whole slip.
                const link = e.rateSource === 'hour' ? hourRateRef : e.rateSource === 'day' ? dayRateRef : null;
                rate.value = link ? ({ formula: link, result: e.rateValue } as any) : e.rateValue;
                rate.numFmt = rateFmt(e.rateUnit);
            } else {
                rate.value = e.rateText;
            }
            applyStyle(rate, rowCenter);

            const canFormula = e.qty !== null && e.rateValue !== null;
            amountCell(
                ws, r, 5, e.amount,
                canFormula ? `C${r}*D${r}` : null,
                canFormula ? (e.qty as number) * (e.rateValue as number) : null,
                earnAmtStyle, INR2,
            );
        } else {
            band(ws, r, 2, 5, '', rowStyle);
        }

        if (d) {
            band(ws, r, 7, 7, d.name, rowStyle);
            const detail = ws.getCell(r, 8);
            if (d.qty !== null) {
                detail.value = d.qty;
                detail.numFmt = qtyFmt(d.qtyUnit, d.integralQty);
            } else {
                detail.value = d.detailsText;
            }
            applyStyle(detail, rowCenter);

            ws.mergeCells(r, 9, r, 10);
            const rate = ws.getCell(r, 9);
            if (d.rateValue !== null) {
                rate.value = d.rateValue;
                rate.numFmt = rateFmt(d.rateUnit);
            } else {
                rate.value = d.rateText;
            }
            for (let c = 9; c <= 10; c++) applyStyle(ws.getCell(r, c), rowCenter);

            // A slab penalty charges once per `slab` occurrences — ROUNDDOWN reproduces
            // the engine's floor division, so raising the count re-prices the penalty.
            const live = d.qty !== null && d.rateValue !== null;
            const formula = !live ? null : d.slab ? `ROUNDDOWN(H${r}/${d.slab},0)*I${r}` : `H${r}*I${r}`;
            const computed = !live ? null : d.slab
                ? Math.floor((d.qty as number) / d.slab) * (d.rateValue as number)
                : (d.qty as number) * (d.rateValue as number);
            amountCell(ws, r, 11, d.amount, formula, computed, dedAmtStyle, INR2_NEG);
        } else {
            band(ws, r, 7, 11, '', rowStyle);
        }

        ws.getRow(r).height = 16;
        r++;
    }
    const varEarnEnd = r - 1;
    const varDedEnd = r - 1;

    // Subtotals for A and 1 (same row, as in the PDF)
    const varEarnSumRow = r;
    band(ws, r, 2, 4, 'Subtotal — Variable Earnings', { bold: true, size: 10, color: C.greenInk, bg: C.greenBg, border: C.greenLine });
    amountCell(
        ws, r, 5, m.totalVariableEarnings,
        m.variableEarnings.length ? `SUM(E${varEarnStart}:E${varEarnEnd})` : null,
        m.variableEarnings.length ? m.variableEarnings.reduce((a, e) => a + e.amount, 0) : null,
        { bold: true, size: 11, color: C.greenInk, align: 'right', bg: C.greenBg, border: C.greenLine }, INR0,
    );
    const attTotalRow = r;
    band(ws, r, 7, 10, 'Total Attendance Adjustments', { bold: true, size: 10, color: C.redInk, bg: C.redBg, border: C.redLine });
    amountCell(
        ws, r, 11, m.totalVariableDeductions,
        m.variableDeductions.length ? `SUM(K${varDedStart}:K${varDedEnd})` : null,
        m.variableDeductions.length ? m.variableDeductions.reduce((a, d) => a + d.amount, 0) : null,
        { bold: true, size: 11, color: C.redInk, align: 'right', bg: C.redBg, border: C.redLine }, INR0_NEG,
    );
    ws.getRow(r).height = 18;
    r += 2;

    // Section labels: B | 2
    band(ws, r, 2, 5, 'B. Fixed Allowances & Benefits', { bold: true, size: 9, color: C.greenInk, bg: C.greenBg });
    band(ws, r, 7, 11, '2. Govt. & Statutory Deductions', { bold: true, size: 9, color: C.redInk, bg: C.redBg });
    ws.getRow(r).height = 16;
    r++;

    band(ws, r, 2, 4, 'DESCRIPTION', thStyle);
    band(ws, r, 5, 5, 'AMOUNT (₹)', { ...thStyle, align: 'right' });
    band(ws, r, 7, 7, 'DESCRIPTION', thStyle);
    band(ws, r, 8, 8, 'TYPE', { ...thStyle, align: 'center' });
    band(ws, r, 9, 9, 'RATE', { ...thStyle, align: 'center' });
    band(ws, r, 10, 10, 'BASE', { ...thStyle, align: 'center' });
    band(ws, r, 11, 11, 'AMOUNT (₹)', { ...thStyle, align: 'right' });
    ws.getRow(r).height = 15;
    r++;

    const fixedEarnStart = r;
    const fixedDedStart = r;
    const parallelRows2 = Math.max(m.fixedEarnings.length, m.fixedDeductions.length, 1);
    // Statutory "Base" cells point at the salary-after-attendance figure, which is
    // written further down — collected here and linked once that row is known.
    const baseCells: { row: number; value: number }[] = [];

    for (let i = 0; i < parallelRows2; i++) {
        const e = m.fixedEarnings[i];
        const d = m.fixedDeductions[i];

        if (e) {
            band(ws, r, 2, 4, e.name, rowStyle);
            amountCell(ws, r, 5, e.amount, null, null, earnAmtStyle, INR2);
        } else {
            band(ws, r, 2, 5, '', rowStyle);
        }

        if (d) {
            band(ws, r, 7, 7, d.name, rowStyle);
            band(ws, r, 8, 8, d.typeLabel, rowCenter);

            const rate = ws.getCell(r, 9);
            if (d.rateValue !== null) {
                rate.value = d.isPercent ? d.rateValue : d.rateValue;
                rate.numFmt = d.isPercent ? '0.00%' : INR2;
            } else {
                rate.value = d.rateText;
            }
            applyStyle(rate, rowCenter);

            const baseCell = ws.getCell(r, 10);
            if (d.base !== null) {
                baseCell.value = d.base;
                baseCell.numFmt = INR0;
                baseCells.push({ row: r, value: d.base });
            } else {
                baseCell.value = '—';
            }
            applyStyle(baseCell, rowCenter);

            const canFormula = d.isPercent && d.rateValue !== null && d.base !== null;
            amountCell(
                ws, r, 11, d.amount,
                canFormula ? `ROUND(J${r}*I${r},0)` : (!d.isPercent && d.rateValue !== null ? `ROUND(I${r},0)` : null),
                canFormula ? Math.round((d.base as number) * (d.rateValue as number)) : (!d.isPercent && d.rateValue !== null ? Math.round(d.rateValue) : null),
                dedAmtStyle, INR0_NEG,
            );
        } else {
            band(ws, r, 7, 11, '', rowStyle);
        }

        ws.getRow(r).height = 16;
        r++;
    }
    const fixedEarnEnd = r - 1;
    const fixedDedEnd = r - 1;

    const fixedEarnSumRow = r;
    band(ws, r, 2, 4, 'Subtotal — Fixed Earnings', { bold: true, size: 10, color: C.greenInk, bg: C.greenBg, border: C.greenLine });
    amountCell(
        ws, r, 5, m.totalFixedEarnings,
        m.fixedEarnings.length ? `SUM(E${fixedEarnStart}:E${fixedEarnEnd})` : null,
        m.fixedEarnings.length ? m.fixedEarnings.reduce((a, e) => a + e.amount, 0) : null,
        { bold: true, size: 11, color: C.greenInk, align: 'right', bg: C.greenBg, border: C.greenLine }, INR0,
    );
    const statTotalRow = r;
    band(ws, r, 7, 10, 'Total Statutory Deductions', { bold: true, size: 10, color: C.redInk, bg: C.redBg, border: C.redLine });
    amountCell(
        ws, r, 11, m.totalFixedDeductions,
        m.fixedDeductions.length ? `SUM(K${fixedDedStart}:K${fixedDedEnd})` : null,
        m.fixedDeductions.length ? m.fixedDeductions.reduce((a, d) => a + d.amount, 0) : null,
        { bold: true, size: 11, color: C.redInk, align: 'right', bg: C.redBg, border: C.redLine }, INR0_NEG,
    );
    ws.getRow(r).height = 18;
    r++;

    // ── PANEL TOTALS ──────────────────────────────────────────────────────────
    const grossRow = r;
    band(ws, r, 2, 4, 'TOTAL EARNINGS (A + B)', { bold: true, size: 11, color: C.white, bg: '#16a34a' });
    const grossCell = ws.getCell(r, 5);
    grossCell.value = { formula: `E${varEarnSumRow}+E${fixedEarnSumRow}`, result: m.totalGrossPay } as any;
    grossCell.numFmt = INR0;
    applyStyle(grossCell, { bold: true, size: 12, color: C.white, align: 'right', bg: '#16a34a' });

    const dedRow = r;
    band(ws, r, 7, 10, 'TOTAL DEDUCTIONS (1 + 2)', { bold: true, size: 11, color: C.white, bg: '#dc2626' });
    const dedCell = ws.getCell(r, 11);
    dedCell.value = { formula: `K${attTotalRow}+K${statTotalRow}`, result: m.totalDeductions } as any;
    dedCell.numFmt = INR0_NEG;
    applyStyle(dedCell, { bold: true, size: 12, color: C.white, align: 'right', bg: '#dc2626' });
    ws.getRow(r).height = 22;
    r += 2;

    // Salary after attendance adjustments (base used by the statutory rows)
    band(ws, r, 2, 8, 'Total Salary After Attendance Adjustments  (Gross Pay − Attendance Deductions)', { bold: true, size: 10, color: C.blueInk, bg: C.blueBg, border: C.blueLine });
    const afterAttCell = ws.getCell(r, 9);
    ws.mergeCells(r, 9, r, 11);
    afterAttCell.value = { formula: `MAX(0,E${grossRow}-K${attTotalRow})`, result: m.salaryAfterAttendance } as any;
    afterAttCell.numFmt = INR0;
    for (let c = 9; c <= 11; c++) applyStyle(ws.getCell(r, c), { bold: true, size: 12, color: C.blueInk, align: 'right', bg: C.blueBg, border: C.blueLine });
    ws.getRow(r).height = 20;
    const afterAttRow = r;
    r++;

    // Link each statutory Base cell to the salary-after-attendance figure.
    baseCells.forEach(b => {
        ws.getCell(b.row, 10).value = { formula: `$I$${afterAttRow}`, result: b.value } as any;
    });

    // ── ROUNDING RECONCILIATION ───────────────────────────────────────────────
    // Where the payroll register's own net differs from earnings − deductions, the
    // gap gets its own visible line rather than freezing the net into a literal.
    // The chain below it stays live and still lands on the official figure.
    let adjRef: string | null = null;
    if (Math.abs(m.netAdjustment) >= 0.005) {
        band(ws, r, 2, 8, 'Rounding & Reconciliation  (to payroll register)', { bold: true, size: 10, color: C.amberInk, bg: C.amberBg, border: '#fde68a' });
        ws.mergeCells(r, 9, r, 11);
        const adjCell = ws.getCell(r, 9);
        adjCell.value = m.netAdjustment;
        adjCell.numFmt = INR2_SIGNED;
        for (let c = 9; c <= 11; c++) applyStyle(ws.getCell(r, c), { bold: true, size: 11, color: C.amberInk, align: 'right', bg: C.amberBg, border: '#fde68a' });
        ws.getRow(r).height = 18;
        adjRef = `I${r}`;
        r++;
    }

    // ── NET PAYABLE ───────────────────────────────────────────────────────────
    const netRow = r;
    band(ws, r, 2, 8, `NET SALARY PAYABLE  (Total Earnings − Total Deductions${adjRef ? ' + Reconciliation' : ''})`, { bold: true, size: 12, color: C.white, bg: C.navy });
    ws.mergeCells(r, 9, r, 11);
    const netCell = ws.getCell(r, 9);
    netCell.value = {
        formula: `E${grossRow}-K${dedRow}${adjRef ? `+${adjRef}` : ''}`,
        result: m.netSalary,
    } as any;
    netCell.numFmt = INR0;
    for (let c = 9; c <= 11; c++) applyStyle(ws.getCell(r, c), { bold: true, size: 14, color: C.white, align: 'right', bg: C.navy });
    ws.getRow(r).height = 26;
    r++;

    band(ws, r, COL.first, COL.last, `Amount in words: ${m.netInWords}`, { italic: true, size: 9, color: C.slate, bg: C.grey, border: C.slateSoft });
    ws.getRow(r).height = 16;
    r += 2;

    // ── SUMMARY CARDS — now that every total exists ───────────────────────────
    const cardGross = ws.getCell(cardRow, 2);
    cardGross.value = { formula: `E${grossRow}`, result: m.totalGrossPay } as any;
    cardGross.numFmt = INR0;
    const cardAtt = ws.getCell(cardRow, 4);
    cardAtt.value = { formula: `K${attTotalRow}`, result: m.totalVariableDeductions } as any;
    cardAtt.numFmt = INR0_NEG;
    const cardDed = ws.getCell(cardRow, 6);
    cardDed.value = { formula: `K${dedRow}`, result: m.totalDeductions } as any;
    cardDed.numFmt = INR0_NEG;
    const cardNet = ws.getCell(cardRow, 9);
    cardNet.value = { formula: `I${netRow}`, result: m.netSalary } as any;
    cardNet.numFmt = INR0;

    // ── SALARY HISTORY ────────────────────────────────────────────────────────
    if (m.salaryHistory.length) {
        band(ws, r, COL.first, COL.last, 'SALARY HISTORY', { bold: true, size: 11, color: C.greenInk, bg: C.greenBg, border: C.greenLine });
        ws.getRow(r).height = 20;
        r++;

        band(ws, r, 2, 4, 'DATE & TIME', thStyle);
        band(ws, r, 5, 6, 'PAYABLE (₹)', { ...thStyle, align: 'right' });
        band(ws, r, 7, 8, 'PAID (₹)', { ...thStyle, align: 'right' });
        band(ws, r, 9, 11, 'REMAINING (₹)', { ...thStyle, align: 'right' });
        ws.getRow(r).height = 15;
        r++;

        const histStart = r;
        m.salaryHistory.forEach((h, i) => {
            band(ws, r, 2, 4, h.paidAt, rowStyle);

            ws.mergeCells(r, 5, r, 6);
            const payable = ws.getCell(r, 5);
            payable.value = { formula: `$I$${netRow}`, result: h.payable } as any;
            payable.numFmt = INR0;
            for (let c = 5; c <= 6; c++) applyStyle(ws.getCell(r, c), { ...rowStyle, align: 'right' });

            ws.mergeCells(r, 7, r, 8);
            const paid = ws.getCell(r, 7);
            paid.value = h.paid;
            paid.numFmt = INR0;
            for (let c = 7; c <= 8; c++) applyStyle(ws.getCell(r, c), { ...rowStyle, align: 'right', bold: true, color: C.greenInk });

            ws.mergeCells(r, 9, r, 11);
            const remaining = ws.getCell(r, 9);
            remaining.value = { formula: `MAX(0,E${r}-SUM($G$${histStart}:G${r}))`, result: h.remaining } as any;
            remaining.numFmt = INR0;
            for (let c = 9; c <= 11; c++) applyStyle(ws.getCell(r, c), { ...rowStyle, align: 'right', bold: true, color: i === m.salaryHistory.length - 1 ? C.blueInk : C.ink });

            ws.getRow(r).height = 16;
            r++;
        });

        band(ws, r, 2, 6, 'TOTAL PAID', { bold: true, size: 10, color: C.greenInk, bg: C.greenBg, border: C.greenLine });
        ws.mergeCells(r, 7, r, 8);
        const totPaid = ws.getCell(r, 7);
        totPaid.value = { formula: `SUM(G${histStart}:G${r - 1})`, result: m.salaryHistory.reduce((a, h) => a + h.paid, 0) } as any;
        totPaid.numFmt = INR0;
        for (let c = 7; c <= 8; c++) applyStyle(ws.getCell(r, c), { bold: true, size: 11, color: C.greenInk, align: 'right', bg: C.greenBg, border: C.greenLine });
        ws.mergeCells(r, 9, r, 11);
        const totRemaining = ws.getCell(r, 9);
        totRemaining.value = { formula: `MAX(0,$I$${netRow}-G${r})`, result: Math.max(0, m.netSalary - m.salaryHistory.reduce((a, h) => a + h.paid, 0)) } as any;
        totRemaining.numFmt = INR0;
        for (let c = 9; c <= 11; c++) applyStyle(ws.getCell(r, c), { bold: true, size: 11, color: C.blueInk, align: 'right', bg: C.greenBg, border: C.greenLine });
        ws.getRow(r).height = 18;
        r += 2;
    }

    // ── PAYMENT SUMMARY ───────────────────────────────────────────────────────
    band(ws, r, COL.first, COL.last, 'PAYMENT SUMMARY', { bold: true, size: 11, color: C.white, bg: C.navyLight });
    ws.getRow(r).height = 20;
    r++;
    const sumRef: Record<string, { addr: string; row: number; col: number; value: number }> = {};
    for (let i = 0; i < m.summary.length; i += 2) {
        ([[m.summary[i], 2, 3, 5], [m.summary[i + 1], 7, 9, 11]] as const).forEach(([item, lblCol, valCol, valEnd]) => {
            if (!item) {
                band(ws, r, lblCol, valEnd, '', valStyle);
                return;
            }
            band(ws, r, lblCol, valCol - 1, item.label, lblStyle);
            const cell = band(ws, r, valCol, valEnd, item.value, { ...valStyle, align: 'right' });
            if (item.money) cell.numFmt = INR0;
            if (typeof item.value === 'number') {
                sumRef[item.label] = { addr: `$${colLetter(valCol)}$${r}`, row: r, col: valCol, value: item.value };
            }
        });
        ws.getRow(r).height = 16;
        r++;
    }

    // Tie the summary back to the slip: what is payable comes from the net row, and
    // every "pending" is its own outstanding balance rather than a copied number.
    const sumRelink = (label: string, formula: string, computed: number) => {
        const target = sumRef[label];
        if (!target || !Number.isFinite(computed) || Math.abs(computed - target.value) >= 0.51) return;
        ws.getCell(target.row, target.col).value = { formula, result: target.value } as any;
    };
    sumRelink('Net Salary Payable', `$I$${netRow}`, m.netSalary);
    if (sumRef['Salary Paid']) {
        sumRelink('Salary Pending', `MAX(0,$I$${netRow}-${sumRef['Salary Paid'].addr})`, Math.max(0, m.netSalary - sumRef['Salary Paid'].value));
    }
    sumRelink('Government Deductions', `K${statTotalRow}`, m.totalFixedDeductions);
    if (sumRef['Government Deductions'] && sumRef['Government Paid']) {
        sumRelink(
            'Government Pending',
            `MAX(0,${sumRef['Government Deductions'].addr}-${sumRef['Government Paid'].addr})`,
            Math.max(0, sumRef['Government Deductions'].value - sumRef['Government Paid'].value),
        );
    }
    if (sumRef['Retention Deducted'] && sumRef['Retention Paid']) {
        sumRelink(
            'Retention Pending',
            `MAX(0,${sumRef['Retention Deducted'].addr}-${sumRef['Retention Paid'].addr})`,
            Math.max(0, sumRef['Retention Deducted'].value - sumRef['Retention Paid'].value),
        );
    }
    if (sumRef['Net Salary Payable'] && sumRef['Government Deductions']) {
        const retention = sumRef['Retention Deducted'];
        sumRelink(
            'Total Company Payout',
            `${sumRef['Net Salary Payable'].addr}+${sumRef['Government Deductions'].addr}${retention ? `+${retention.addr}` : ''}`,
            sumRef['Net Salary Payable'].value + sumRef['Government Deductions'].value + (retention?.value ?? 0),
        );
    }
    r++;

    // ── METADATA ──────────────────────────────────────────────────────────────
    band(ws, r, 2, 3, 'GENERATED BY', { bold: true, size: 8, color: C.muted, bg: C.grey, border: C.slateSoft });
    band(ws, r, 4, 6, 'PAYSLIP REFERENCE', { bold: true, size: 8, color: C.muted, bg: C.grey, border: C.slateSoft });
    band(ws, r, 7, 11, 'NOTE', { bold: true, size: 8, color: C.muted, bg: C.grey, border: C.slateSoft });
    ws.getRow(r).height = 14;
    r++;
    band(ws, r, 2, 3, m.generatedBy, { bold: true, size: 10, bg: C.white, border: C.slateSoft });
    band(ws, r, 4, 6, m.payslipId, { bold: true, size: 10, bg: C.white, border: C.slateSoft });
    band(ws, r, 7, 11, 'System-generated document. No physical signature required.', { size: 9, color: C.muted, bg: C.white, border: C.slateSoft, italic: true });
    ws.getRow(r).height = 18;
    r += 2;

    // ── SIGNATURE — a self-contained block in columns I:K ─────────────────────
    // "For and on behalf of" → stamp → signature rule → company → signatory,
    // all centred on the same three columns so the stack reads as one unit.
    const stamp = await tryAddImage(wb, m.companyStamp);
    band(ws, r, 9, 11, 'For and on behalf of', { size: 8, color: C.muted, align: 'center', bg: C.white });
    ws.getRow(r).height = 15;
    r++;

    const stampRows = stamp ? 4 : 2;
    block(ws, r, 9, r + stampRows - 1, 11, '', { bg: C.white, align: 'center' });
    for (let i = 0; i < stampRows; i++) ws.getRow(r + i).height = stamp ? 19 : 13;
    if (stamp) {
        // Bottom padding keeps the stamp clear of the signature rule below it.
        placeImageInPlate(ws, stamp, r, 9, r + stampRows - 1, 11, 8, 12, 1, 84, 84);
    }
    r += stampRows;

    band(ws, r, 9, 11, `( ${m.companyName} )`, { bold: true, size: 10, align: 'center', color: C.ink, borderTop: '#64748b' });
    ws.getRow(r).height = 18;
    r++;
    band(ws, r, 9, 11, 'AUTHORIZED SIGNATORY', { size: 7.5, align: 'center', color: C.muted });
    ws.getRow(r).height = 13;
    r += 2;

    // ── FOOTER ────────────────────────────────────────────────────────────────
    band(ws, r, COL.first, COL.last, '🔒  CONFIDENTIAL — This payslip is strictly confidential and intended solely for the named employee. Unauthorized use is prohibited.',
        { size: 8, color: C.white, align: 'center', bg: C.navy });
    ws.getRow(r).height = 18;

    ws.pageSetup.printArea = `A1:K${r}`;

    // ── SHEET 2: full payment ledger ──────────────────────────────────────────
    if (m.ledger.length) {
        const ps = wb.addWorksheet('Payment Ledger', { views: [{ showGridLines: false }] });
        ps.columns = [
            { width: 6 }, { width: 24 }, { width: 13 }, { width: 24 }, { width: 17 },
            { width: 22 }, { width: 16 }, { width: 16 }, { width: 16 }, { width: 15 }, { width: 30 },
        ];
        const headers = ['#', 'Date & Time', 'Type', 'Component', 'Method', 'Transaction ID', 'Paid (₹)', 'Payable (₹)', 'Remaining (₹)', 'Status', 'Remarks'];

        let pr = 1;
        band(ps, pr, 1, headers.length, `PAYMENT LEDGER — ${m.employeeName}  ·  ${m.payMonth}`, { bold: true, size: 14, color: C.white, align: 'center', bg: C.navy });
        ps.getRow(pr).height = 26;
        pr += 2;

        headers.forEach((h, i) => {
            const cell = ps.getCell(pr, i + 1);
            cell.value = h;
            applyStyle(cell, { bold: true, size: 10, color: C.white, align: 'center', bg: C.navyLight, border: '#1e293b' });
        });
        ps.getRow(pr).height = 20;
        ps.views = [{ state: 'frozen', ySplit: pr, showGridLines: false }];
        pr++;

        const ledgerStart = pr;
        m.ledger.forEach((row, i) => {
            const stripe = i % 2 === 0 ? C.white : C.grey;
            const values: any[] = [i + 1, row.date, row.type, row.component, row.method, row.txn, row.paid, row.payable, row.remaining, row.status, row.remarks];
            values.forEach((v, ci) => {
                const cell = ps.getCell(pr, ci + 1);
                cell.value = v;
                const isMoney = ci >= 6 && ci <= 8;
                if (isMoney) cell.numFmt = INR0;
                applyStyle(cell, {
                    size: 10,
                    bold: isMoney,
                    color: ci === 6 ? C.greenInk : C.ink,
                    bg: stripe,
                    align: isMoney ? 'right' : ci === 0 ? 'center' : 'left',
                    border: C.slateSoft,
                });
            });
            ps.getRow(pr).height = 16;
            pr++;
        });

        const totalCell = ps.getCell(pr, 7);
        band(ps, pr, 1, 6, 'TOTAL PAID', { bold: true, size: 11, color: C.blueInk, bg: C.blueBg, border: C.blueLine });
        totalCell.value = { formula: `SUM(G${ledgerStart}:G${pr - 1})`, result: m.totalPaid } as any;
        totalCell.numFmt = INR0;
        applyStyle(totalCell, { bold: true, size: 11, color: C.blueInk, align: 'right', bg: C.blueBg, border: C.blueLine });
        for (let c = 8; c <= headers.length; c++) applyStyle(ps.getCell(pr, c), { bg: C.blueBg, border: C.blueLine });
        ps.getRow(pr).height = 20;
    }

    const buffer = await wb.xlsx.writeBuffer();
    saveAs(
        new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
        `${m.fileName}.xlsx`,
    );
}

// ─── CSV ──────────────────────────────────────────────────────────────────────

const csvEscape = (v: any): string => {
    const s = v === null || v === undefined ? '' : String(v);
    return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

const csvNum = (n: number) => csvEscape(Number(num(n).toFixed(2)));

/**
 * CSV export.
 *
 * Laid out on a fixed five-column grid — A Description · B Details · C Rate ·
 * D Base · E Amount — so that every money figure sits in one predictable column
 * and can carry a real formula. Excel and Google Sheets both evaluate formulas
 * when they open a CSV, so this file recalculates on edit exactly like the .xlsx.
 * Numbers are written plain (no ₹, no grouping) to stay machine-readable.
 */
export function downloadSalarySlipCsv(input: SalarySlipExportInput): void {
    const m = buildSlipModel(input);
    const L: string[] = [];
    const row = (...cells: any[]) => L.push(cells.map(csvEscape).join(','));
    /** 1-based spreadsheet row the NEXT `row()` call will occupy. */
    const at = () => L.length + 1;
    /** A formula, but only when it reproduces the engine's own figure. */
    const calc = (formula: string, computed: number | null, expected: number) =>
        computed !== null && Math.abs(computed - expected) < 0.51 ? `=${formula}` : Number(expected.toFixed(2));

    row(m.companyName);
    row('MONTHLY PAYROLL STATEMENT - SALARY SLIP');
    row(m.companyAddress);
    row(m.companyContact, m.companyWebsite);
    row(m.companyReg);
    L.push('');

    row('Pay Month', m.payMonth, 'Pay Period', m.payPeriod);
    row('Payslip ID', m.payslipId, 'Generated On', m.generatedOn);
    row('Generated By', m.generatedBy);
    L.push('');

    row('EMPLOYEE DETAILS');
    row('Employee Name', m.employeeName, 'Employee Code', m.employeeCode);
    row('Designation', m.designation, 'Department', m.department);
    row('Joining Date', m.joiningDate, 'Employment Type', m.employmentType);
    row('PAN Number', m.panNumber, 'Company Email', m.companyEmail);
    row('Bank Name', m.bankName, 'A/C No (Last 4)', m.accountNo);
    row('IFSC Code', m.ifscCode, 'Payment Status', m.paymentStatus);
    L.push('');

    row('ATTENDANCE, TIME & SALARY RATES');
    row('Description', 'Value');
    const csvRef: Record<string, string> = {};
    [...m.attendance, ...m.rates].forEach(a => {
        if (typeof a.value === 'number') csvRef[a.label] = `$B$${at()}`;
        row(a.label, typeof a.value === 'number' ? Number(a.value.toFixed(4)) : a.value);
    });
    L.push('');

    // Rate references let each earning line point at the master rate, so editing the
    // per-hour rate re-prices the entire slip — the same wiring as the .xlsx.
    const rateRef = { hour: csvRef['Per Hour Rate'] ?? null, day: csvRef['Per Day Rate'] ?? null };

    row('A. VARIABLE EARNINGS (WORK-BASED)');
    row('Description', 'Details', 'Rate', 'Base', 'Amount');
    const varEarnFrom = at();
    m.variableEarnings.forEach(e => {
        const line = at();
        const link = e.rateSource ? rateRef[e.rateSource] : null;
        row(
            e.name,
            e.qty !== null ? Number(e.qty.toFixed(4)) : e.detailsText,
            e.rateValue !== null ? (link ? `=${link}` : Number(e.rateValue.toFixed(4))) : e.rateText,
            '',
            e.qty !== null && e.rateValue !== null
                ? calc(`B${line}*C${line}`, e.qty * e.rateValue, e.amount)
                : Number(e.amount.toFixed(2)),
        );
    });
    const varEarnTo = at() - 1;
    const varEarnSum = at();
    row('Subtotal - Variable Earnings', '', '', '',
        m.variableEarnings.length ? `=SUM(E${varEarnFrom}:E${varEarnTo})` : Number(m.totalVariableEarnings.toFixed(2)));
    L.push('');

    row('B. FIXED ALLOWANCES & BENEFITS');
    row('Description', '', '', '', 'Amount');
    const fixedEarnFrom = at();
    m.fixedEarnings.forEach(e => row(e.name, '', '', '', Number(e.amount.toFixed(2))));
    const fixedEarnTo = at() - 1;
    const fixedEarnSum = at();
    row('Subtotal - Fixed Earnings', '', '', '',
        m.fixedEarnings.length ? `=SUM(E${fixedEarnFrom}:E${fixedEarnTo})` : Number(m.totalFixedEarnings.toFixed(2)));
    const grossLine = at();
    row('TOTAL EARNINGS (A + B)', '', '', '', `=E${varEarnSum}+E${fixedEarnSum}`);
    L.push('');

    row('1. ATTENDANCE ADJUSTMENTS');
    row('Description', 'Details', 'Rate', 'Base', 'Amount');
    const varDedFrom = at();
    m.variableDeductions.forEach(d => {
        const line = at();
        const live = d.qty !== null && d.rateValue !== null;
        const formula = d.slab ? `ROUNDDOWN(B${line}/${d.slab},0)*C${line}` : `B${line}*C${line}`;
        const computed = !live ? null : d.slab
            ? Math.floor((d.qty as number) / d.slab) * (d.rateValue as number)
            : (d.qty as number) * (d.rateValue as number);
        row(
            d.name,
            d.qty !== null ? Number(d.qty.toFixed(4)) : d.detailsText,
            d.rateValue !== null ? Number(d.rateValue.toFixed(4)) : d.rateText,
            '',
            live ? calc(formula, computed, d.amount) : Number(d.amount.toFixed(2)),
        );
    });
    const varDedTo = at() - 1;
    const attTotalLine = at();
    row('Total Attendance Adjustments', '', '', '',
        m.variableDeductions.length ? `=SUM(E${varDedFrom}:E${varDedTo})` : Number(m.totalVariableDeductions.toFixed(2)));
    const afterAttLine = at();
    row('Total Salary After Attendance Adjustments', '', '', '', `=MAX(0,E${grossLine}-E${attTotalLine})`);
    L.push('');

    row('2. GOVT. & STATUTORY DEDUCTIONS');
    row('Description', 'Type', 'Rate', 'Base', 'Amount');
    const fixedDedFrom = at();
    m.fixedDeductions.forEach(d => {
        const line = at();
        // Percentage rates go in as fractions so `Base × Rate` works; the Type column
        // carries the human reading of the same figure.
        const percentFormula = d.isPercent && d.rateValue !== null && d.base !== null;
        row(
            d.name,
            d.isPercent ? `${d.typeLabel} (${d.rateText})` : d.typeLabel,
            d.rateValue !== null ? Number(d.rateValue.toFixed(6)) : d.rateText,
            d.base === null ? '' : `=E${afterAttLine}`,
            percentFormula
                ? calc(`ROUND(D${line}*C${line},0)`, Math.round((d.base as number) * (d.rateValue as number)), d.amount)
                : !d.isPercent && d.rateValue !== null
                    ? calc(`ROUND(C${line},0)`, Math.round(d.rateValue), d.amount)
                    : Number(d.amount.toFixed(2)),
        );
    });
    const fixedDedTo = at() - 1;
    const statTotalLine = at();
    row('Total Statutory Deductions', '', '', '',
        m.fixedDeductions.length ? `=SUM(E${fixedDedFrom}:E${fixedDedTo})` : Number(m.totalFixedDeductions.toFixed(2)));
    const dedTotalLine = at();
    row('TOTAL DEDUCTIONS (1 + 2)', '', '', '', `=E${attTotalLine}+E${statTotalLine}`);
    L.push('');

    let adjLine: number | null = null;
    if (Math.abs(m.netAdjustment) >= 0.005) {
        adjLine = at();
        row('Rounding & Reconciliation (to payroll register)', '', '', '', Number(m.netAdjustment.toFixed(2)));
    }
    const netLine = at();
    row('NET SALARY PAYABLE', '', '', '', `=E${grossLine}-E${dedTotalLine}${adjLine ? `+E${adjLine}` : ''}`);
    row('Amount in words', m.netInWords);
    L.push('');

    if (m.salaryHistory.length) {
        row('SALARY HISTORY');
        row('Date & Time', 'Payable', 'Paid', 'Remaining');
        const histFrom = at();
        m.salaryHistory.forEach(h => {
            const line = at();
            // Each row's remaining balance is what is payable less everything paid up
            // to and including that instalment.
            row(h.paidAt, `=$E$${netLine}`, Number(h.paid.toFixed(2)), `=MAX(0,B${line}-SUM($C$${histFrom}:C${line}))`);
        });
        const histTo = at() - 1;
        row('TOTAL PAID', '', `=SUM(C${histFrom}:C${histTo})`, `=MAX(0,$E$${netLine}-C${at()})`);
        L.push('');
    }

    row('PAYMENT SUMMARY');
    row('Description', 'Amount');
    const summaryRef: Record<string, { addr: string; value: number }> = {};
    m.summary.forEach(item => {
        if (typeof item.value === 'number') summaryRef[item.label] = { addr: `$B$${at()}`, value: item.value };
        row(item.label, typeof item.value === 'number' ? Number(item.value.toFixed(2)) : item.value);
    });
    // Rewrite the derived figures in place as formulas, keeping the same guard the
    // .xlsx uses: a definition that does not reproduce the engine's number is dropped.
    const rewrite = (label: string, formula: string, computed: number) => {
        const target = summaryRef[label];
        if (!target || !Number.isFinite(computed) || Math.abs(computed - target.value) >= 0.51) return;
        const idx = Number(target.addr.split('$')[2]) - 1;
        L[idx] = [csvEscape(label), `=${formula}`].join(',');
    };
    rewrite('Net Salary Payable', `$E$${netLine}`, m.netSalary);
    if (summaryRef['Salary Paid']) {
        rewrite('Salary Pending', `MAX(0,$E$${netLine}-${summaryRef['Salary Paid'].addr})`, Math.max(0, m.netSalary - summaryRef['Salary Paid'].value));
    }
    rewrite('Government Deductions', `$E$${statTotalLine}`, m.totalFixedDeductions);
    if (summaryRef['Government Deductions'] && summaryRef['Government Paid']) {
        rewrite(
            'Government Pending',
            `MAX(0,${summaryRef['Government Deductions'].addr}-${summaryRef['Government Paid'].addr})`,
            Math.max(0, summaryRef['Government Deductions'].value - summaryRef['Government Paid'].value),
        );
    }
    if (summaryRef['Retention Deducted'] && summaryRef['Retention Paid']) {
        rewrite(
            'Retention Pending',
            `MAX(0,${summaryRef['Retention Deducted'].addr}-${summaryRef['Retention Paid'].addr})`,
            Math.max(0, summaryRef['Retention Deducted'].value - summaryRef['Retention Paid'].value),
        );
    }
    if (summaryRef['Net Salary Payable'] && summaryRef['Government Deductions']) {
        const retention = summaryRef['Retention Deducted'];
        rewrite(
            'Total Company Payout',
            `${summaryRef['Net Salary Payable'].addr}+${summaryRef['Government Deductions'].addr}${retention ? `+${retention.addr}` : ''}`,
            summaryRef['Net Salary Payable'].value + summaryRef['Government Deductions'].value + (retention?.value ?? 0),
        );
    }
    L.push('');

    row('PAYMENT LEDGER');
    row('#', 'Date & Time', 'Type', 'Component', 'Method', 'Transaction ID', 'Paid', 'Payable', 'Remaining', 'Status', 'Remarks');
    if (!m.ledger.length) {
        row('No payments recorded for this month');
    } else {
        const ledgerFrom = at();
        m.ledger.forEach((l, i) => L.push([
            csvEscape(i + 1), csvEscape(l.date), csvEscape(l.type), csvEscape(l.component), csvEscape(l.method),
            csvEscape(l.txn), csvNum(l.paid), csvNum(l.payable), csvNum(l.remaining), csvEscape(l.status), csvEscape(l.remarks),
        ].join(',')));
        L.push(['TOTAL', '', '', '', '', '', `=SUM(G${ledgerFrom}:G${at() - 1})`].join(','));
    }
    L.push('');
    row('CONFIDENTIAL - This payslip is intended solely for the named employee.');
    row(`( ${m.companyName} )`, 'AUTHORIZED SIGNATORY');

    // BOM keeps ₹ and other UTF-8 characters readable when Excel opens the file.
    saveAs(new Blob(['﻿' + L.join('\r\n')], { type: 'text/csv;charset=utf-8' }), `${m.fileName}.csv`);
}
