import React from 'react';
import { Dropdown } from 'react-bootstrap';
import { useSelector } from 'react-redux';
import { KTIcon } from '@metronic/helpers';
import { SalarySlipProps } from '@pages/employee/salary/utils/salarySlipDataTransformer';
import { uploadUserAsset } from '@services/uploader';
import { sendSalarySlipToEmployee } from '@services/employee';
import { fetchCompanyOverview } from '@services/company';
import { errorConfirmation } from '@utils/modal';
import { toast } from 'react-toastify';
import { RootState } from '@redux/store';
import { payrollService } from '@modules/payroll/services/payrollService';
import { downloadSalarySlipXlsx, downloadSalarySlipCsv } from '@modules/payroll/utils/salarySlipExport';

interface SalarySlipSectionProps {
    salarySlipProps: SalarySlipProps | null;
    userId: string;
    employeeId: string;
    salaryId: string;
    /** Payroll month (1-12) — used to fetch the slip when the month has no saved salary record yet. */
    month?: number;
    /** Payroll year — see `month`. */
    year?: number;
    loading: boolean;
    setLoading: (loading: boolean) => void;
    employee?: any;
    /** Raw monthly salary record — source for the Excel / CSV export. */
    apiSalaryData?: any;
    /** Month totals from useSalaryCalculations — exported in the Payment Summary block. */
    summaryData?: any;
    /** Payment ledger rows from useSalaryCalculations — exported as the Payment History sheet. */
    paymentRows?: any[];
    resolveName?: (name: string) => string;
    resolveComponent?: (name: string) => any | null;
}

const SalarySlipSection: React.FC<SalarySlipSectionProps> = ({
    salarySlipProps,
    userId,
    employeeId,
    salaryId,
    month,
    year,
    loading,
    setLoading,
    employee,
    apiSalaryData,
    summaryData,
    paymentRows,
    resolveName,
    resolveComponent
}) => {
    const [isDownloading, setIsDownloading] = React.useState(false);
    const [isSending, setIsSending] = React.useState(false);
    const [isDownloadingBill, setIsDownloadingBill] = React.useState(false);
    const [isExporting, setIsExporting] = React.useState<'xlsx' | 'csv' | null>(null);

    // Logged-in user — shown as "Generated By" on the exported slip, like the PDF.
    const currentUser = useSelector((state: RootState) => state.employee.currentEmployee);
    const generatedBy = `${currentUser?.users?.firstName || ''} ${currentUser?.users?.lastName || ''}`.replace(/\s+/g, ' ').trim() || 'Payroll System';

    const isContractEmployee = !!employee?.professionalFeesEnabled;

    // Single source for the slip PDF — always the backend template.
    // Finalised months are fetched by salary id; a month with no salary record yet
    // (the in-progress current month) is fetched by employee + month/year so the
    // very same template is rendered from live figures.
    const canFetchSlip = !!salaryId || (!!employeeId && !!month && !!year);

    const fetchSlipBlob = async (): Promise<Blob> => {
        if (salaryId) return payrollService.downloadSalarySlip(salaryId);
        return payrollService.downloadSalarySlipForPeriod(employeeId, month as number, year as number);
    };

    const slipFileName = `${salarySlipProps?.employee?.users?.firstName || ''} ${salarySlipProps?.employee?.users?.lastName || ''} Salary Slip ${salarySlipProps?.date || ''}.pdf`.trim();

    const handleDownloadPdf = async () => {
        setLoading(true);
        setIsDownloading(true);
        try {
            const blob = await fetchSlipBlob();
            const url = window.URL.createObjectURL(new Blob([blob]));
            const link = document.createElement('a');
            link.href = url;
            link.setAttribute('download', slipFileName);
            document.body.appendChild(link);
            link.click();
            link.parentNode?.removeChild(link);
            window.URL.revokeObjectURL(url);
        } catch (e) {
            console.error(e);
            errorConfirmation("Failed to download PDF");
        } finally {
            setLoading(false);
            setIsDownloading(false);
        }
    };

    // Excel / CSV are built in the browser from the same month record the Financial
    // Breakdown renders, so the sheet always reconciles with the screen and the PDF.
    const canExportSheet = !!apiSalaryData && !!month && !!year;

    // Company branding for the exported slip header/signature — fetched once, on demand.
    const companyRef = React.useRef<any>(null);
    const resolveCompany = async () => {
        if (companyRef.current) return companyRef.current;
        const attached = (employee as any)?.companyOverview;
        if (attached) {
            companyRef.current = attached;
            return attached;
        }
        try {
            const { data: { companyOverview } } = await fetchCompanyOverview();
            const list = Array.isArray(companyOverview) ? companyOverview : [companyOverview];
            companyRef.current = list.find((c: any) => c?.id === employee?.companyId) ?? list[0] ?? null;
        } catch (err) {
            console.warn('Company overview unavailable for the export header:', err);
            companyRef.current = null;
        }
        return companyRef.current;
    };

    const handleSheetExport = async (format: 'xlsx' | 'csv') => {
        if (!canExportSheet) return;
        setIsExporting(format);
        try {
            const payload = {
                employee,
                apiSalaryData,
                summaryData,
                paymentRows,
                month: month as number,
                year: year as number,
                company: await resolveCompany(),
                generatedBy,
                resolveName,
                resolveComponent,
            };
            if (format === 'xlsx') await downloadSalarySlipXlsx(payload);
            else downloadSalarySlipCsv(payload);
        } catch (e) {
            console.error(e);
            errorConfirmation(`Failed to export ${format === 'xlsx' ? 'Excel' : 'CSV'} file`);
        } finally {
            setIsExporting(null);
        }
    };

    const downloadBtnStyle: React.CSSProperties = {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '5px',
        padding: '7px 14px',
        border: '1.5px solid #e2e8f0',
        borderRadius: '6px',
        background: '#f8fafc',
        color: '#475569',
        fontWeight: 500,
        fontSize: '12px',
        cursor: loading ? 'not-allowed' : 'pointer',
        opacity: loading ? 0.6 : 1,
        transition: 'all 0.2s ease',
        whiteSpace: 'nowrap',
    };

    const downloadLabel = isDownloading
        ? 'Generating…'
        : isExporting === 'xlsx'
            ? 'Building Excel…'
            : isExporting === 'csv'
                ? 'Building CSV…'
                : 'Download Slip';

    const handleDownloadContractBill = async () => {
        if (!salaryId) return;
        setLoading(true);
        setIsDownloadingBill(true);
        try {
            const blob = await payrollService.downloadContractBill(salaryId);
            const url = window.URL.createObjectURL(new Blob([blob]));
            const link = document.createElement('a');
            link.href = url;
            const empName = `${employee?.users?.firstName || ''} ${employee?.users?.lastName || ''}`.trim();
            const monthYear = new Date().toLocaleDateString('en-IN', {
                month: 'short',
                year: 'numeric'
            });
            link.setAttribute('download', `Contract_Bill_${empName}_${monthYear}.pdf`.trim());
            document.body.appendChild(link);
            link.click();
            link.parentNode?.removeChild(link);
        } catch (e) {
            console.error(e);
            errorConfirmation('Failed to download contract bill PDF');
        } finally {
            setLoading(false);
            setIsDownloadingBill(false);
        }
    };

    const handleEmailSalarySlip = async () => {
        if (!salarySlipProps || !canFetchSlip) {
            alert('No salary data available for PDF generation');
            return;
        }

        setLoading(true);
        setIsSending(true);
        try {
            // Fetch the PDF generated by Puppeteer in the backend
            const blob = await fetchSlipBlob();
            const form = new FormData();
            const fileFinal = new File([blob], `${userId}-SalarySlip-${Date.now()}.pdf`, { type: 'application/pdf' });
            form.append("file", fileFinal);
            
            const { data: { path } } = await uploadUserAsset(form, userId, "salaryreport", "salary-docs");
            
            const res = await sendSalarySlipToEmployee({
                path,
                employeeId,
                salaryData: salarySlipProps
            });

            if (res?.statusCode === 200 && !res.hasError) {
                const email = salarySlipProps.employee?.companyEmailId || (salarySlipProps.employee as any)?.users?.personalEmailId || 'Employee';
                toast.success(
                    <div style={{ display: 'flex', flexDirection: 'column' }}>
                        <div style={{ fontWeight: 700, color: '#0f172a', marginBottom: '4px', fontSize: '0.95rem' }}>Email Sent Successfully</div>
                        <div style={{ fontSize: '0.8rem', color: '#64748b', marginBottom: '8px' }}>Salary slip delivered to:</div>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                            <div style={{ display: 'inline-flex', alignItems: 'center', backgroundColor: '#f8fafc', padding: '6px 10px', borderRadius: '8px', fontSize: '0.8rem', color: '#334155', fontWeight: 600, border: '1px solid #e2e8f0' }}>
                                <span style={{ marginRight: '8px', fontSize: '1.1em' }}>✉️</span>
                                {email}
                            </div>
                        </div>
                    </div>,
                    {
                        position: 'bottom-right',
                        autoClose: 6000,
                        style: {
                            borderRadius: '12px',
                            padding: '16px',
                            border: '1px solid #e2e8f0',
                            boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)'
                        }
                    }
                );
            } else {
                errorConfirmation("Failed to send salary slip. Please try again.");
            }
        } catch (error) {
            console.error("Failed to send salary slip:", error);
            errorConfirmation("Failed to send salary slip. Please try again.");
        } finally {
            setLoading(false);
            setIsSending(false);
        }
    };

    return (
        // pointerEvents:auto + filter:none keep these actions clickable & crisp even when an
        // ancestor carries the `sensitive-data-hidden` class (eye closed) which sets
        // pointer-events:none. Slip download/email are not sensitive data, so they stay accessible.
        <div
            className="d-flex flex-wrap justify-content-end align-items-center mb-4"
            style={{ pointerEvents: 'auto', filter: 'none', gap: '8px' }}
        >
            {salarySlipProps && (canFetchSlip || canExportSheet) ? (
                <Dropdown align="end">
                    <Dropdown.Toggle
                        as="button"
                        type="button"
                        id="salary-slip-download"
                        disabled={loading || isExporting !== null}
                        style={downloadBtnStyle}
                        onMouseEnter={e => { if (!loading) { (e.currentTarget as HTMLButtonElement).style.background = '#f1f5f9'; (e.currentTarget as HTMLButtonElement).style.borderColor = '#cbd5e1'; } }}
                        onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = '#f8fafc'; (e.currentTarget as HTMLButtonElement).style.borderColor = '#e2e8f0'; }}
                    >
                        <KTIcon iconName="file-down" className="fs-6" />
                        <span>{downloadLabel}</span>
                    </Dropdown.Toggle>

                    {/* Absolute (default) positioning only — a `fixed` strategy is resolved against
                        the nearest transformed ancestor in the Metronic layout, not the viewport,
                        which threw the menu into the page corner. */}
                    <Dropdown.Menu
                        renderOnMount
                        style={{ minWidth: '250px', borderRadius: '10px', border: '1px solid #e2e8f0', boxShadow: '0 8px 24px rgba(15,23,42,0.10)', padding: '6px', zIndex: 1055 }}
                    >
                        <Dropdown.Item
                            onClick={handleDownloadPdf}
                            disabled={!canFetchSlip}
                            style={{ borderRadius: '8px', padding: '8px 10px' }}
                        >
                            <div className="d-flex align-items-center gap-3">
                                <KTIcon iconName="file-down" className="fs-4 text-danger" />
                                <div>
                                    <div className="fw-bold fs-7 text-gray-800">PDF (.pdf)</div>
                                    <div className="fs-8 text-muted">Official salary slip document</div>
                                </div>
                            </div>
                        </Dropdown.Item>

                        <Dropdown.Divider style={{ margin: '4px 0' }} />

                        <Dropdown.Item
                            onClick={() => handleSheetExport('xlsx')}
                            disabled={!canExportSheet}
                            style={{ borderRadius: '8px', padding: '8px 10px' }}
                        >
                            <div className="d-flex align-items-center gap-3">
                                <KTIcon iconName="chart-simple" className="fs-4 text-success" />
                                <div>
                                    <div className="fw-bold fs-7 text-gray-800">Excel (.xlsx)</div>
                                    <div className="fs-8 text-muted">Full month data, totals & payments</div>
                                </div>
                            </div>
                        </Dropdown.Item>

                        <Dropdown.Item
                            onClick={() => handleSheetExport('csv')}
                            disabled={!canExportSheet}
                            style={{ borderRadius: '8px', padding: '8px 10px' }}
                        >
                            <div className="d-flex align-items-center gap-3">
                                <KTIcon iconName="document" className="fs-4 text-primary" />
                                <div>
                                    <div className="fw-bold fs-7 text-gray-800">CSV (.csv)</div>
                                    <div className="fs-8 text-muted">Plain data for any spreadsheet</div>
                                </div>
                            </div>
                        </Dropdown.Item>
                    </Dropdown.Menu>
                </Dropdown>
            ) : (
                <button disabled style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', padding: '7px 14px', border: '1.5px solid #e2e8f0', borderRadius: '6px', background: '#f8fafc', color: '#94a3b8', fontWeight: 500, fontSize: '12px', cursor: 'not-allowed', whiteSpace: 'nowrap' }}>
                    <KTIcon iconName="file-down" className="fs-6" />
                    <span>No PDF Data</span>
                </button>
            )}

            {isContractEmployee && salaryId && (
                <button
                    onClick={handleDownloadContractBill}
                    disabled={loading}
                    style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        gap: '5px',
                        padding: '7px 14px',
                        border: '1.5px solid #e2e8f0',
                        borderRadius: '6px',
                        background: '#f8fafc',
                        color: '#475569',
                        fontWeight: 500,
                        fontSize: '12px',
                        cursor: loading ? 'not-allowed' : 'pointer',
                        opacity: loading ? 0.6 : 1,
                        transition: 'all 0.2s ease',
                        whiteSpace: 'nowrap',
                    }}
                    onMouseEnter={e => { if (!loading) { (e.currentTarget as HTMLButtonElement).style.background = '#f1f5f9'; (e.currentTarget as HTMLButtonElement).style.borderColor = '#cbd5e1'; } }}
                    onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = '#f8fafc'; (e.currentTarget as HTMLButtonElement).style.borderColor = '#e2e8f0'; }}
                >
                    <KTIcon iconName="file-down" className="fs-6" />
                    <span>{isDownloadingBill ? 'Downloading...' : 'Download Bill'}</span>
                </button>
            )}

            {salarySlipProps && (
                <button
                    onClick={handleEmailSalarySlip}
                    disabled={loading}
                    style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        gap: '5px',
                        padding: '7px 14px',
                        border: 'none',
                        borderRadius: '6px',
                        background: loading ? '#d32f2f' : '#d32f2f',
                        color: '#fff',
                        fontWeight: 500,
                        fontSize: '12px',
                        cursor: loading ? 'not-allowed' : 'pointer',
                        boxShadow: '0 2px 6px rgba(211,47,47,0.2)',
                        transition: 'all 0.2s ease',
                        whiteSpace: 'nowrap',
                    }}
                    onMouseEnter={e => { if (!loading) { (e.currentTarget as HTMLButtonElement).style.background = '#b71c1c'; (e.currentTarget as HTMLButtonElement).style.boxShadow = '0 4px 12px rgba(211,47,47,0.3)'; } }}
                    onMouseLeave={e => { if (!loading) { (e.currentTarget as HTMLButtonElement).style.background = '#d32f2f'; (e.currentTarget as HTMLButtonElement).style.boxShadow = '0 2px 6px rgba(211,47,47,0.2)'; } }}
                >
                    <KTIcon iconName="sms" className="fs-6" />
                    <span>{isSending ? 'Sending…' : 'Email Slip'}</span>
                </button>
            )}
        </div>
    );
};

export default React.memo(SalarySlipSection);
