import React from 'react';
import { KTIcon } from '@metronic/helpers';
import { PDFDownloadLink, pdf } from '@react-pdf/renderer';
import SalarySlipTemplate from '@pages/employee/salary/SalarySlipTemplate';
import { SalarySlipProps } from '@pages/employee/salary/utils/salarySlipDataTransformer';
import { uploadUserAsset } from '@services/uploader';
import { sendSalarySlipToEmployee } from '@services/employee';
import { successConfirmation, errorConfirmation } from '@utils/modal';
import { toast } from 'react-toastify';
import { payrollService } from '@modules/payroll/services/payrollService';

interface SalarySlipSectionProps {
    salarySlipProps: SalarySlipProps | null;
    userId: string;
    employeeId: string;
    salaryId: string;
    loading: boolean;
    setLoading: (loading: boolean) => void;
}

const SalarySlipSection: React.FC<SalarySlipSectionProps> = ({
    salarySlipProps,
    userId,
    employeeId,
    salaryId,
    loading,
    setLoading
}) => {
    const [isDownloading, setIsDownloading] = React.useState(false);
    const [isSending, setIsSending] = React.useState(false);
    const handleEmailSalarySlip = async () => {
        if (!salarySlipProps || !salaryId) {
            alert('No salary data available for PDF generation');
            return;
        }

        setLoading(true);
        setIsSending(true);
        try {
            // Fetch the PDF generated by Puppeteer in the backend
            const blob = await payrollService.downloadSalarySlip(salaryId);
            const form = new FormData();
            const fileFinal = new File([blob], `${userId}-SalarySlip-${Date.now()}.pdf`, { type: 'application/pdf' });
            form.append("file", fileFinal);
            
            const { data: { path } } = await uploadUserAsset(form, userId, "salaryreport", "salary-docs");
            
            const res = await sendSalarySlipToEmployee({
                path,
                employeeId,
                salaryData: salarySlipProps
            });

            if (res?.statusCode === 200 && !res.hasError) {
                const email = salarySlipProps.employee?.companyEmailId || 'Employee';
                toast.success(
                    <div style={{ display: 'flex', flexDirection: 'column' }}>
                        <div style={{ fontWeight: 700, color: '#0f172a', marginBottom: '4px', fontSize: '0.95rem' }}>Email Sent Successfully</div>
                        <div style={{ fontSize: '0.8rem', color: '#64748b', marginBottom: '8px' }}>Salary slip delivered to:</div>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                            <div style={{ display: 'inline-flex', alignItems: 'center', backgroundColor: '#f8fafc', padding: '6px 10px', borderRadius: '8px', fontSize: '0.8rem', color: '#334155', fontWeight: 600, border: '1px solid #e2e8f0' }}>
                                <span style={{ marginRight: '8px', fontSize: '1.1em' }}>✉️</span>
                                {email}
                            </div>
                        </div>
                    </div>,
                    {
                        position: 'bottom-right',
                        autoClose: 6000,
                        style: {
                            borderRadius: '12px',
                            padding: '16px',
                            border: '1px solid #e2e8f0',
                            boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)'
                        }
                    }
                );
            } else {
                errorConfirmation("Failed to send salary slip. Please try again.");
            }
        } catch (error) {
            console.error("Failed to send salary slip:", error);
            errorConfirmation("Failed to send salary slip. Please try again.");
        } finally {
            setLoading(false);
            setIsSending(false);
        }
    };

    return (
        <div className="d-flex flex-wrap justify-content-end align-items-center mb-4 gap-3">
            {salarySlipProps && salaryId ? (
                <button
                    disabled={loading}
                    onClick={async () => {
                        setLoading(true);
                        setIsDownloading(true);
                        try {
                            const blob = await payrollService.downloadSalarySlip(salaryId);
                            const url = window.URL.createObjectURL(new Blob([blob]));
                            const link = document.createElement('a');
                            link.href = url;
                            link.setAttribute('download', `${salarySlipProps.employee?.users?.firstName || ''} ${salarySlipProps.employee?.users?.lastName || ''} Salary Slip ${salarySlipProps.date || ''}.pdf`.trim());
                            document.body.appendChild(link);
                            link.click();
                            link.parentNode?.removeChild(link);
                        } catch (e) {
                            console.error(e);
                            errorConfirmation("Failed to download PDF");
                        } finally {
                            setLoading(false);
                            setIsDownloading(false);
                        }
                    }}
                    style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '8px',
                        padding: '10px 22px',
                        border: '1.5px solid #AA393D',
                        borderRadius: '8px',
                        background: 'transparent',
                        color: '#AA393D',
                        fontWeight: 600,
                        fontSize: '14px',
                        cursor: loading ? 'not-allowed' : 'pointer',
                        opacity: loading ? 0.6 : 1,
                        transition: 'all 0.2s',
                    }}
                    onMouseEnter={e => { if (!loading) { (e.currentTarget as HTMLButtonElement).style.background = '#AA393D'; (e.currentTarget as HTMLButtonElement).style.color = '#fff'; } }}
                    onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = 'transparent'; (e.currentTarget as HTMLButtonElement).style.color = '#AA393D'; }}
                >
                    <KTIcon iconName="file-down" className="fs-4" />
                    {isDownloading ? 'Generating…' : 'Download Salary Slip'}
                </button>
            ) : (
                <button disabled style={{ padding: '10px 22px', border: '1.5px solid #e2e8f0', borderRadius: '8px', background: '#f8fafc', color: '#94a3b8', fontWeight: 600, fontSize: '14px', cursor: 'not-allowed' }}>
                    No PDF Data
                </button>
            )}

            {salarySlipProps && (
                <button
                    onClick={handleEmailSalarySlip}
                    disabled={loading}
                    style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '8px',
                        padding: '10px 22px',
                        border: '1.5px solid transparent',
                        borderRadius: '8px',
                        background: loading ? '#c8797b' : '#AA393D',
                        color: '#fff',
                        fontWeight: 600,
                        fontSize: '14px',
                        cursor: loading ? 'not-allowed' : 'pointer',
                        boxShadow: '0 2px 8px rgba(170,57,61,0.25)',
                        transition: 'all 0.2s',
                    }}
                    onMouseEnter={e => { if (!loading) (e.currentTarget as HTMLButtonElement).style.background = '#8e2d30'; }}
                    onMouseLeave={e => { if (!loading) (e.currentTarget as HTMLButtonElement).style.background = '#AA393D'; }}
                >
                    <KTIcon iconName="sms" className="fs-4" />
                    {isSending ? 'Sending…' : 'Email Salary Slip'}
                </button>
            )}
        </div>
    );
};

export default React.memo(SalarySlipSection);
