import React from 'react';
import { KTIcon } from '@metronic/helpers';
import { PDFDownloadLink, pdf } from '@react-pdf/renderer';
import SalarySlipTemplate from '@pages/employee/salary/SalarySlipTemplate';
import { SalarySlipProps } from '@pages/employee/salary/utils/salarySlipDataTransformer';
import { uploadUserAsset } from '@services/uploader';
import { sendSalarySlipToEmployee } from '@services/employee';
import { successConfirmation, errorConfirmation } from '@utils/modal';
import { toast } from 'react-toastify';
import { payrollService } from '@modules/payroll/services/payrollService';

interface SalarySlipSectionProps {
    salarySlipProps: SalarySlipProps | null;
    userId: string;
    employeeId: string;
    salaryId: string;
    loading: boolean;
    setLoading: (loading: boolean) => void;
    employee?: any;
}

const SalarySlipSection: React.FC<SalarySlipSectionProps> = ({
    salarySlipProps,
    userId,
    employeeId,
    salaryId,
    loading,
    setLoading,
    employee
}) => {
    const [isDownloading, setIsDownloading] = React.useState(false);
    const [isSending, setIsSending] = React.useState(false);
    const [isDownloadingBill, setIsDownloadingBill] = React.useState(false);

    const isContractEmployee = !!employee?.professionalFeesEnabled;

    const handleDownloadContractBill = async () => {
        if (!salaryId) return;
        setLoading(true);
        setIsDownloadingBill(true);
        try {
            const blob = await payrollService.downloadContractBill(salaryId);
            const url = window.URL.createObjectURL(new Blob([blob]));
            const link = document.createElement('a');
            link.href = url;
            const empName = `${employee?.users?.firstName || ''} ${employee?.users?.lastName || ''}`.trim();
            const monthYear = new Date().toLocaleDateString('en-IN', {
                month: 'short',
                year: 'numeric'
            });
            link.setAttribute('download', `Contract_Bill_${empName}_${monthYear}.pdf`.trim());
            document.body.appendChild(link);
            link.click();
            link.parentNode?.removeChild(link);
        } catch (e) {
            console.error(e);
            errorConfirmation('Failed to download contract bill PDF');
        } finally {
            setLoading(false);
            setIsDownloadingBill(false);
        }
    };

    const handleEmailSalarySlip = async () => {
        if (!salarySlipProps || !salaryId) {
            alert('No salary data available for PDF generation');
            return;
        }

        setLoading(true);
        setIsSending(true);
        try {
            // Fetch the PDF generated by Puppeteer in the backend
            const blob = await payrollService.downloadSalarySlip(salaryId);
            const form = new FormData();
            const fileFinal = new File([blob], `${userId}-SalarySlip-${Date.now()}.pdf`, { type: 'application/pdf' });
            form.append("file", fileFinal);
            
            const { data: { path } } = await uploadUserAsset(form, userId, "salaryreport", "salary-docs");
            
            const res = await sendSalarySlipToEmployee({
                path,
                employeeId,
                salaryData: salarySlipProps
            });

            if (res?.statusCode === 200 && !res.hasError) {
                const email = salarySlipProps.employee?.companyEmailId || (salarySlipProps.employee as any)?.users?.personalEmailId || 'Employee';
                toast.success(
                    <div style={{ display: 'flex', flexDirection: 'column' }}>
                        <div style={{ fontWeight: 700, color: '#0f172a', marginBottom: '4px', fontSize: '0.95rem' }}>Email Sent Successfully</div>
                        <div style={{ fontSize: '0.8rem', color: '#64748b', marginBottom: '8px' }}>Salary slip delivered to:</div>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                            <div style={{ display: 'inline-flex', alignItems: 'center', backgroundColor: '#f8fafc', padding: '6px 10px', borderRadius: '8px', fontSize: '0.8rem', color: '#334155', fontWeight: 600, border: '1px solid #e2e8f0' }}>
                                <span style={{ marginRight: '8px', fontSize: '1.1em' }}>✉️</span>
                                {email}
                            </div>
                        </div>
                    </div>,
                    {
                        position: 'bottom-right',
                        autoClose: 6000,
                        style: {
                            borderRadius: '12px',
                            padding: '16px',
                            border: '1px solid #e2e8f0',
                            boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)'
                        }
                    }
                );
            } else {
                errorConfirmation("Failed to send salary slip. Please try again.");
            }
        } catch (error) {
            console.error("Failed to send salary slip:", error);
            errorConfirmation("Failed to send salary slip. Please try again.");
        } finally {
            setLoading(false);
            setIsSending(false);
        }
    };

    return (
        // pointerEvents:auto + filter:none keep these actions clickable & crisp even when an
        // ancestor carries the `sensitive-data-hidden` class (eye closed) which sets
        // pointer-events:none. Slip download/email are not sensitive data, so they stay accessible.
        <div
            className="d-flex flex-wrap justify-content-end align-items-center mb-4"
            style={{ pointerEvents: 'auto', filter: 'none', gap: '8px' }}
        >
            {salarySlipProps && salaryId ? (
                <button
                    disabled={loading}
                    onClick={async () => {
                        setLoading(true);
                        setIsDownloading(true);
                        try {
                            const blob = await payrollService.downloadSalarySlip(salaryId);
                            const url = window.URL.createObjectURL(new Blob([blob]));
                            const link = document.createElement('a');
                            link.href = url;
                            link.setAttribute('download', `${salarySlipProps.employee?.users?.firstName || ''} ${salarySlipProps.employee?.users?.lastName || ''} Salary Slip ${salarySlipProps.date || ''}.pdf`.trim());
                            document.body.appendChild(link);
                            link.click();
                            link.parentNode?.removeChild(link);
                        } catch (e) {
                            console.error(e);
                            errorConfirmation("Failed to download PDF");
                        } finally {
                            setLoading(false);
                            setIsDownloading(false);
                        }
                    }}
                    style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        gap: '5px',
                        padding: '7px 14px',
                        border: '1.5px solid #e2e8f0',
                        borderRadius: '6px',
                        background: '#f8fafc',
                        color: '#475569',
                        fontWeight: 500,
                        fontSize: '12px',
                        cursor: loading ? 'not-allowed' : 'pointer',
                        opacity: loading ? 0.6 : 1,
                        transition: 'all 0.2s ease',
                        whiteSpace: 'nowrap',
                    }}
                    onMouseEnter={e => { if (!loading) { (e.currentTarget as HTMLButtonElement).style.background = '#f1f5f9'; (e.currentTarget as HTMLButtonElement).style.borderColor = '#cbd5e1'; } }}
                    onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = '#f8fafc'; (e.currentTarget as HTMLButtonElement).style.borderColor = '#e2e8f0'; }}
                >
                    <KTIcon iconName="file-down" className="fs-6" />
                    <span>{isDownloading ? 'Generating…' : 'Download Slip'}</span>
                </button>
            ) : (
                <button disabled style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', padding: '7px 14px', border: '1.5px solid #e2e8f0', borderRadius: '6px', background: '#f8fafc', color: '#94a3b8', fontWeight: 500, fontSize: '12px', cursor: 'not-allowed', whiteSpace: 'nowrap' }}>
                    <KTIcon iconName="file-down" className="fs-6" />
                    <span>No PDF Data</span>
                </button>
            )}

            {isContractEmployee && salaryId && (
                <button
                    onClick={handleDownloadContractBill}
                    disabled={loading}
                    style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        gap: '5px',
                        padding: '7px 14px',
                        border: '1.5px solid #e2e8f0',
                        borderRadius: '6px',
                        background: '#f8fafc',
                        color: '#475569',
                        fontWeight: 500,
                        fontSize: '12px',
                        cursor: loading ? 'not-allowed' : 'pointer',
                        opacity: loading ? 0.6 : 1,
                        transition: 'all 0.2s ease',
                        whiteSpace: 'nowrap',
                    }}
                    onMouseEnter={e => { if (!loading) { (e.currentTarget as HTMLButtonElement).style.background = '#f1f5f9'; (e.currentTarget as HTMLButtonElement).style.borderColor = '#cbd5e1'; } }}
                    onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = '#f8fafc'; (e.currentTarget as HTMLButtonElement).style.borderColor = '#e2e8f0'; }}
                >
                    <KTIcon iconName="file-down" className="fs-6" />
                    <span>{isDownloadingBill ? 'Downloading...' : 'Download Bill'}</span>
                </button>
            )}

            {salarySlipProps && (
                <button
                    onClick={handleEmailSalarySlip}
                    disabled={loading}
                    style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        gap: '5px',
                        padding: '7px 14px',
                        border: 'none',
                        borderRadius: '6px',
                        background: loading ? '#d32f2f' : '#d32f2f',
                        color: '#fff',
                        fontWeight: 500,
                        fontSize: '12px',
                        cursor: loading ? 'not-allowed' : 'pointer',
                        boxShadow: '0 2px 6px rgba(211,47,47,0.2)',
                        transition: 'all 0.2s ease',
                        whiteSpace: 'nowrap',
                    }}
                    onMouseEnter={e => { if (!loading) { (e.currentTarget as HTMLButtonElement).style.background = '#b71c1c'; (e.currentTarget as HTMLButtonElement).style.boxShadow = '0 4px 12px rgba(211,47,47,0.3)'; } }}
                    onMouseLeave={e => { if (!loading) { (e.currentTarget as HTMLButtonElement).style.background = '#d32f2f'; (e.currentTarget as HTMLButtonElement).style.boxShadow = '0 2px 6px rgba(211,47,47,0.2)'; } }}
                >
                    <KTIcon iconName="sms" className="fs-6" />
                    <span>{isSending ? 'Sending…' : 'Email Slip'}</span>
                </button>
            )}
        </div>
    );
};

export default React.memo(SalarySlipSection);
