import { get } from "lodash"

export const AUTH = {
    LOGIN: "api/auth/login",
    LOGOUT: "api/auth/logout",
    RESET_PASSWORD: "api/auth/resetPassword/:resetToken",
    CHANGE_PASSWORD: "api/auth/changePassword",
    FORGOT_PASSWORD: "api/auth/forgotPassword"
}

export const USERS = {
    CREATE_USER: "api/users",
    ARCHIVE_USER: "api/users/:userId",
    UPDATE_USER: "api/users/:userId",
    FETCH_USER_BY_ID: "api/users/:userId",
    GET_ALL_USERS: "api/users",
    SAVE_USER_TABLE_PREFERENCES: '/api/users/table-preferences',
    GET_USER_TABLE_PREFERENCES: '/api/users/table-preferences/:employeeId/:tableName',
}

export const COMPANY = {
    CREATE_DESIGNATION: "api/company/designations",
    GET_ALL_DESIGNATION: "api/company/designations",
    UPDATE_DESIGNATION_BY_ID: "api/company/designations/:designationId",
    CREATE_BRANCHES: "api/company/branches",
    GET_ALL_BRANCHES: "api/company/branches",
    GET_BRANCH_BY_ID: "api/company/branch/:branchId",
    UPDATE_BRANCH_BY_ID: "api/company/branch/:branchId",
    CREATE_DEPARTMENTS: "api/company/departments",
    GET_ALL_DEPARTMENTS: "api/company/departments",
    GET_DEPARTMENT_BY_ID: "api/company/department/:departmentId",
    UPDATE_DEPARTMENT_BY_ID: "api/company/department/:departmentId",
    CREATE_PUBLIC_HOLIDAYS: "api/company/public-holidays",
    DELETE_PUBLIC_HOLIDAY_BY_ID: "api/company/public-holiday",
    UPDATE_PUBLIC_HOLIDAY_BY_ID: "api/company/public-holiday",
    UPDATE_HOLIDAY_BY_ID: "api/company/holiday-options",
    DELETE_HOLIDAY_BY_ID: "api/company/holiday-options",
    GET_ALL_PUBLIC_HOLIDAYS: "api/company/public-holidays",
    GET_ALL_PUBLIC_HOLIDAYS_BY_COMPANY: "api/company/public-holidays-all",
    GET_ALL_HOLIDAYS: "api/company/holidays",
    CREATE_HOLIDAY: "api/company/holiday",
    GET_LOGO: "api/company/logo",
    CREATE_OVERVIEW: "api/company/overview",
    GET_OVERVIEW: "api/company/overview",
    UPDATE_OVERVIEW: "api/company/overview",
    GET_CONFIGURATION: "api/feature/config",

    GET_ALL_FAQS: "api/company/faqs",
    POST_FAQ: "api/company/faq",
    UPDATE_FAQ_BY_ID: "api/company/faq/:faqId",
    DELETE_FAQ: "api/company/faq/",

    POST_CONFIGURATION: "api/feature/config",
    GET_ANNOUNCEMENT_BY_ID: "api/company/announcement",
    CREATE_ANNOUNCEMENT: "api/company/announcement",
    UPDATE_ANNOUNCEMENT_BY_ID: "api/company/announcement",
    ARCHIVE_ANNOUNCEMENT_BY_ID: "api/company/announcement",
    GET_ALL_ANNOUNCEMENTS: "api/company/announcements",
    UPDATE_ANNOUNCEMENT: "api/company/announcements",
    EMAIL_SALARY_SLIP: "api/employee/email-salary-slip",
    GET_LEAVE_OPTIONS: "api/company/leave-options",
    UPDATE_LEAVE_OPTION_BY_ID: "api/company/leave-option",
    GET_ALL_LOAN: "api/employee/loans",
    GET_ALL_LOAN_INSTALLMENT: "api/company/loan/installment",
    GET_ALL_LOAN_SUMMARY: "api/company/loan/summary",
    GET_ALL_LOAN_DETAILS: "api/company/loan/details",
    GET_MONTHLY_INSTALLMENT_SUMMARY: "api/company/loans/monthly-installment-summary",
    GET_SALARY_DATA_DATE_RANGE_MONTHLY: "api/company/salary/date-range/monthly",
    CREATE_SALARY_HISTORY: "api/company/salary-history",
    GET_SALARY_HISTORY: "api/company/salary-history",
    UPDATE_SALARY_HISTORY: "api/company/salary-history",

    GET_ALL_SUB_COMPANIES: 'api/lead-project-companies/sub-companies',
    GET_SUB_COMPANY_BY_ID: 'api/lead-project-companies/sub-companies/:id',
    CREATE_SUB_COMPANY: 'api/lead-project-companies/sub-companies',
    UPDATE_SUB_COMPANY: 'api/lead-project-companies/sub-companies/:id',
    DELETE_SUB_COMPANY: 'api/lead-project-companies/sub-companies/:id',
    GET_SUB_COMPANIES_BY_MAIN_COMPANY_ID: 'api/lead-project-companies/sub-companies/main-company/:mainCompanyId',
    GET_SUB_COMPANIES_BY_COMPANY_ID: 'api/lead-project-companies/client-companies/:companyId/sub-companies',
}

export const EMPLOYEE = {
    CREATE_EMPLOYEE: "api/employee",
    GET_ALL_EMPLOYEE: "api/employee/all",
    GET_ALL_EMPLOYEE_SELECTED_DATA: "api/employee/all-employees-selected-data",
    GET_EMPLOYEE_DISCRETIONARY_BALANCE: "api/employee/discretionary-balance/:id",
    GET_ALL_LEAVES: "api/employee/employee-on-leaves",
    EMAIL_ATTENDANCE_REQUEST_LIMIT_RESET: "api/employee/email/attendance-request-limit-reset",
    GET_ATTENDANCE_REQUEST_LIMIT_RESET_REQUESTS: "api/employee/attendance-request-limit-reset/requests",
    APPROVE_ATTENDANCE_REQUEST_LIMIT_RESET: "api/employee/attendance-request-limit-reset/approve",
    REJECT_ATTENDANCE_REQUEST_LIMIT_RESET: "api/employee/attendance-request-limit-reset/reject",
    UPDATE_EMPLOYEE_BY_ID: "api/employee",
    GET_EMPLOYEE_BY_ID: "api/employee",
    CREATE_EMERGENCY_CONTACTS: "api/employee/emergencyContacts",
    GET_EMERGENCY_CONTACTS_BY_EMP_ID: "api/employee/emergencyContacts/:employeeId",
    UPDATE_EMERGENCY_CONTACT_BY_ID: "api/employee/emergencyContacts",
    CREATE_EMERGENCY_DETAILS: "api/employee/emergency-details",
    UPDATE_EMERGENCY_DETAILS_BY_ID: "api/employee/emergency-details",
    GET_EMERGENCY_DETAILS: "api/employee/emergency-details?employeeId=",
    CREATE_ONBOARDING_DOC_LIST: "api/employee/onboarding-documents",
    GET_ONBOARDING_DOC_LIST: "api/employee/onboarding-documents",
    CREATE_BANK_DETAILS: "api/employee/bank-details",
    UPDATE_BANK_DETAILS_BY_ID: "api/employee/bank-details",
    GET_BANK_DETAILS: "api/employee/bank-details?employeeId=",
    CREATE_EDUCATIONAL_DETAILS: "api/employee/educational-details",
    GET_EDUCATIONAL_DETAILS: "api/employee/educational-details?employeeId=",
    UPDATE_EDUCATIONAL_DETAILS_BY_ID: "api/employee/educational-details",
    CREATE_REJOIN_HISTORY: "api/employee/rejoin-history",
    FETCH_REJOIN_HISTORY: "api/employee/rejoin-history?employeeId=",
    UPDATE_REJOIN_HISTORY_BY_ID: "api/employee/rejoin-history",
    DELETE_REJOIN_HISTORY_BY_ID: "api/employee/rejoin-history",
    DELETE_ALL_REJOIN_HISTORY_BY_EMPLOYEE_ID: "api/employee/rejoin-history/employee",
    CREATE_PREVIOUS_EXPERIENCE: "api/employee/previous-experience",
    UPDATE_PREVIOUS_EXPERIENCE_BY_ID: "api/employee/previous-experience",
    GET_PREVIOUS_EXPERIENCE: "api/employee/previous-experience?employeeId=",
    CREATE_ADDRESS_DETAILS: "api/employee/address-details",
    UPDATE_ADDRESS_DETAILS_BY_ID: "api/employee/address-details",
    CREATE_DOCUMENTS_DETAILS: "api/employee/documents-details",
    UPDATE_DOCUMENTS_DETAILS_BY_ID: "api/employee/documents-details",
    UPDATE_ONBOARDING_DOCUMENT_DETAILS_BY_ID: "api/employee/onboarding-documents",
    GET_DOCUMENTS_DETAILS: "api/employee/documents-details",
    GET_ATTENDANCE_BY_EMP_ID: "api/employee/attendance",
    GET_ALL_ATTENDANCE: "api/employee/attendance/all",
    CREATE_EMPLOYEE_ATTENDANCE: "api/employee/attendance",
    CHECK_ATTENDANCE_MARKED: "api/employee/attendance/marked",
    MARK_CHECKOUT_ATTENDANCE: "api/employee/attendance",
    VALIDATE_IN_OUT_TOKEN: "api/employee/validate-token-in-out",
    LEAVE_BALANCE: "api/employee/leave-balance",
    LEAVES: "api/employee/leaves",
    GET_WIZARD_DATA: "api/employee/wizard",
    GET_ADDRESS_DETAILS: "api/employee/address-details?employeeId=",
    CREATE_EMPLOYEE_LEAVE_REQUEST: "api/employee/leave-request",
    DELETE_EMPLOYEE_LEAVE_REQUEST: "api/employee/leave-request",
    GET_EMPLOYEE_LEAVE_REQUEST: "api/employee/leave-request",
    LEAVE_ACTION: "api/employee/leave-action",
    CREATE_LEAVE_OPTION: "api/company/leave-option",
    UPDATE_LEAVE_OPTION_BY_ID: "api/company/leave-option",
    EMPLOYEE_ATTENDANCE_STATISTICS: "api/employee/attendance/stats",
    GET_REIMBURSEMENT: "api/employee/reimbursement",
    CREATE_REIMBURSEMENT: "api/employee/reimbursement",
    EMPLOYEE_ATTENDANCE_RECORDS: "api/employee/attendance/records",
    DELETE_REIMBURSEMENT: "api/employee/reimbursement",
    UPDATE_REIMBURSEMENT_BY_ID: "api/employee/reimbursement",
    APPROVE_MULTIPLE_REIMBURSEMENTS: "api/employee/reimbursements/approve-multiple",
    GROSS_PAY_DEDUCTIONS: "api/company/gross-pay-deductions",
    GROSS_PAY_CONFIG: "api/company/employee/gross-pay-config",
    GROSS_PAY_CONFIG_BY_ID: "api/company/employee/:employeeId/gross-pay-config",
    GROSS_PAY_CONFIG_HISTORY: "api/company/employee/:employeeId/gross-pay-config/history",
    DEDUCTION_CONFIG: "api/company/employee/deduction-config",
    DEDUCTION_CONFIG_BY_ID: "api/company/employee/:employeeId/deduction-config",
    DEDUCTION_CONFIG_HISTORY: "api/company/employee/:employeeId/deduction-config/history",
    SALARY: "api/company/salary",
    CREATE_ATTENDANCE_REQUEST: "api/employee/attendance/request",
    GET_ATTENDANCE_REQUEST: "api/employee/attendance/request",
    GET_ALL_ATTENDANCE_REQUEST: "api/employee/attendance/requests",
    GET_PENDING_ATTENDANCE_REQUESTS: "api/employee/attendance/pending-requests",
    DELETE_ATTENDANCE_REQUEST: "api/employee/attendance/",
    APPROVE_ATTENDANCE_REQUEST: "api/employee/attendance/approve-request",
    REJECT_ATTENDANCE_REQUEST: "api/employee/attendance/reject-request",
    GET_ALL_ATTENDANCE_DETAILS_BY_ID: "api/employee/allattendance",
    GET_MEDIA_BY_USER_ID: "api/employee/media-details",
    GET_SALARY_BY_FISCAL_YEAR: "api/company/get-salary-by-fiscal-year",
    GET_SALARY_DATA_FOR_DATE_RANGE_YEARLY: "api/company/salary/date-range/yearly",
    GET_SALARY_DATA_FOR_DATE_RANGE_MONTHLY: "api/company/salary/date-range/monthly",
    GET_SALARY_DATA_FOR_DATE_RANGE_ALL_TIME: "api/company/salary/date-range/all-time",
    GET_SALARAY_RECORDS_BASED_ON_DATE_RANGE: "api/company/salary/records/date-range",
    GET_SALARY_RECORDS_ALL_ACTIVE_EMPLOYEES: "api/company/salary/records/date-range/all-active-employees",
    GET_PAID_SALARY_RECORDS: "api/company/salary/records",
    GET_Total_salary_By_Year: "api/company/get-total-salaryByYear",
    GET_TOTAL_MONTHLY_SALARY: "api/company/get-total-monthly-salary",
    CREATE_TODOS: "api/employee/todo",
    UPDATE_TODOS: "api/employee/todo",
    GET_TODOS: "api/employee/todo",
    DELETE_TODOS: "api/employee/todo",
    CREATE_MEETINGS: "api/employee/meetings",
    GET_MEETINGS: "api/employee/meetings",
    UPDATE_MEETING: "/api/employee/meetings",
    DELETE_MEETING: "/api/employee/meetings",
    UPDATE_EMPLOYEE_ROLES: "api/employee/:id/roles",
    GET_EMPLOYEE_PERMISSIONS: "api/employee/:id/permissions",
    CREATE_EMPLOYEE_PERMISSION: "api/employee/:id/permissions",
    UPDATE_EMPLOYEE_PERMISSION: "api/employee/:id/permissions/:permissionId",
    DELETE_EMPLOYEE_PERMISSION: "api/employee/:id/permissions/:permissionId",
    CREATE_NOTIFICATION: "api/employee/notification",
    GET_NOTIFICATIONS: "api/employee/notification",
    GET_ALL_NOTIFICATIONS: "api/employee/allnotification",
    MARK_ALL_AS_READ: "api/employee/mark-all-read",
    EMAIL_SALARY_SLIP: "api/employee/email-salary-slip",
    GET_LOAN_BY_EMPLOYEE_ID: "api/employee/loans/employee",
    CREATE_LOAN: "api/employee/loan",
    GET_INSTALLMENT_BY_LOAN_ID: "api/employee/loan/installment",
    GET_LOAN_BY_ID: "api/employee/loan",
    DELETE_LOAN_BY_ID: "api/employee/loan",
    UPDATE_LOAN_BY_ID: "api/employee/loan",
    SKIP_LOAN_INSTALLMENT_BY_ID: "api/employee/loan/installment/skip",
    CUSTOM_PAID_LOAN_INSTALLMENT_BY_ID: "api/employee/loan/installment/custom-paid",
    GET_MONTHLY_INSTALLMENT_BY_EMPLOYEE_ID: "api/employee/loans/installments/custom-date",
    UPDATE_LOAN_INSTALLMENT_BY_ID: "api/employee/loan/installment",
    APPROVE_LOAN_BY_ID: "api/employee/loan/approve",
    CREATE_KPI_MODULE: "api/employee/kpi/module",
    GET_ALL_KPI_MODULES: "api/employee/kpi/module",
    CREATE_KPI_FACTOR: "api/employee/kpi/factor",
    UPDATE_KPI_FACTOR: "api/employee/kpi/factor",
    GET_SINGLE_KPI_FACTOR: "api/employee/kpi/factor",
    GET_ALL_KPI_FACTORS: "api/employee/kpi/factors",
    GET_KPI_SCORES_FOR_DAY: "api/employee/kpi/score/day",
    GET_KPI_SCORES_FOR_PERIOD: "api/employee/kpi/scores/period",
    GET_KPI_SCORES_ALL_TIME: 'api/employee/kpi/alltime',
    GET_ALL_STAR_EMPLOYEES_BY_EACH_FACTOR: "api/employee/kpi/star-employees/all",
    CREATE_KPI_SCORE: "api/employee/kpi/score",
    GET_ALL_EMPLOYEE_WITH_MONTH_DAILY_HOURLY_SALARY: "api/employee/all-employees-salary",

    // // Enhanced team management endpoints
    GET_ALL_TEAMS_MEMBER: "api/employee/teams/members",
    CREATE_TEAM_MEMBER: "api/employee/teams/member",
    UPDATE_TEAM_MEMBER: "api/employee/teams/member",
    DELETE_TEAM_MEMBER: "api/employee/teams/member",
    GET_TEAM_MEMBER_BY_ID: "api/employee/teams/member",

    // Enhanced employee level management endpoints
    GET_ALL_EMPLOYEE_LEVELS: "api/employee-levels",
    GET_EMPLOYEE_LEVEL_BY_ID: "api/employee-levels/:id",
    CREATE_EMPLOYEE_LEVEL: "api/employee-levels/create",
    UPDATE_EMPLOYEE_LEVEL: "api/employee-levels/:id",
    DELETE_EMPLOYEE_LEVEL: "api/employee-levels/:id",
    ASSIGN_EMPLOYEE_TO_LEVEL: "api/employee/level/assign",
    REMOVE_EMPLOYEE_FROM_LEVEL: "api/employee/level/remove",

    GET_ALL_EMPLOYEE_MEMBERS: 'api/employee-levels/employee/member',
    GET_EMPLOYEE_MEMBER_BY_ID: 'api/employee-levels/employee/members/:id',
    CREATE_EMPLOYEE_MEMBER: 'api/employee-levels/employee/member',
    CREATE_MULTIPLE_EMPLOYEE_MEMBERS: 'api/employee-levels/employee/membermany',
    UPDATE_EMPLOYEE_MEMBER: 'api/employee-levels/employee/members/:id',
    DELETE_EMPLOYEE_MEMBER: 'api/employee-levels/employee/members/:id',


    CREATE_LEAVE_MANAGEMENT: "api/employee/leave-management",
    GET_LEAVE_MANAGEMENT_BY_ID: "api/employee/leave-management",
    GET_ALL_LEAVE_MANAGEMENTS: "api/employee/leave-management/all",
    UPDATE_LEAVE_MANAGEMENT: "api/employee/leave-management",
    REVOKE_LEAVE_MANAGEMENT: "api/employee/leave-management/revoke",
    DELETE_LEAVE_MANAGEMENT: "api/employee/leave-management/:id"
}

export const CALENDAR = {
    CREATE_EVENT: "api/calendar/event",
    GET_ALL_EMPLOYEE_EVENTS: "api/calendar/events",
    DELETE_EVENT: "api/calendar/event"
}

export const FILE = {
    UPLOAD: "api/files/upload"
}

export const OPTIONS = {
    // Prefix Settings
    GET_ALL_PREFIX_SETTINGS: 'api/options/prefix-settings',
    CREATE_PREFIX_SETTING: 'api/options/prefix-settings',
    UPDATE_PREFIX_SETTING: 'api/options/prefix-settings/:id',
    DELETE_PREFIX_SETTING: 'api/options/prefix-settings/:id',
    COUNTRIES: 'api/options/countries',
    STATES: 'api/options/states',
    CITIES: 'api/options/cities',
    TOWNS: 'api/options/towns',
    CREATE_TOWN: 'api/options/towns',
    UPDATE_TOWN_BY_ID: 'api/options/towns',
    CREATE_WORKING_METHODS: "api/options/working-methods",
    GET_WORKING_METHODS: "api/options/working-methods",
    CREATE_SOURCE_OF_HIRE: "api/options/source-of-hire",
    GET_SOURCE_OF_HIRE: "api/options/source-of-hire",
    CREATE_EMPLOYEE_STATUS: "api/options/employee-status",
    GET_EMPLOYEE_STATUS: "api/options/employee-status",
    CREATE_EMPLOYEE_TYPES: "api/options/employee-types",
    UPDATE_EMPLOYEE_TYPE_BY_ID: "api/options/employee-type",
    GET_EMPLOYEE_TYPES: "api/options/employee-types",
    GET_ALL_REIMBURSEMENT_TYPES: "api/options/reimbursements",
    DELETE_REIMBURSEMENT_TYPES_BY_ID: "api/options/reimbursement",
    CREATE_REIMBURSEMENT_TYPE: "api/options/reimbursement",
    UPDATE_REIMBURSEMENT_TYPE_BY_ID: "api/options/reimbursement",
    GET_COMPANY_SETTINGS: "api/options/settings",
    UPDATE_COMPANY_SETTINGS: "api/options/settings",
    GET_ALL_COLORS: "api/options/colors",
    UPDATE_COLOR_BY_ID: "api/options/colors",
    CREATE_COLOR: "api/options/colors",
    CREATE_ADDON_LEAVES_ALLOWANCE: "api/options/addon-leaves-allowance",
    GET_ALL_ADDON_LEAVES_ALLOWANCES: "api/options/addon-leaves-allowance",
    GET_ADDON_LEAVES_ALLOWANCE_BY_ID: "api/options/addon-leaves-allowance/:id",
    UPDATE_ADDON_LEAVES_ALLOWANCE: "api/options/addon-leaves-allowance/:id",
    DELETE_ADDON_LEAVES_ALLOWANCE: "api/options/addon-leaves-allowance/:id",
    UPSERT_EMPLOYEE_LPC_CHART_SETTINGS: "api/options/employee-lpc-chart-settings",
    GET_EMPLOYEE_LPC_CHART_SETTINGS: "api/options/employee-lpc-chart-settings",
    GET_CURRENCIES: "api/options/currencies",
}

export const LOCATION = {
    ADDRESS: 'api/location/address'
}

export const ROLES = {
    GET_ALL_ROLES: "api/roles",
    GET_ROLE: "api/roles/:id",
    CREATE_ROLE: "api/roles",
    UPDATE_ROLE: "api/roles/:id",
    DELETE_ROLE: "api/roles/:id",
    GET_PERMISSIONS_FOR_ROLE: "api/roles/:id/permissions",
    CREATE_PERMISSION_FOR_ROLE: "api/roles/:id/permissions",
    UPDATE_PERMISSION_FOR_ROLE: "api/roles/:roleId/permissions/:permissionId",
    DELETE_PERMISSION_FOR_ROLE: "api/roles/:roleId/permissions/:permissionId",
}

export const DAY_WISE_SHIFT = {
    GET_ALL_DAY_WISE_SHIFTS: "api/day-wise-shift",
    GET_DAY_WISE_SHIFT: "api/day-wise-shift/:id",
    CREATE_DAY_WISE_SHIFT: "api/day-wise-shift",
    UPDATE_DAY_WISE_SHIFT: "api/day-wise-shift/:id",
    DELETE_DAY_WISE_SHIFT: "api/day-wise-shift/:id",
}


export const LEAD_PROJECT_COMPANY = {
    GET_ALL_LEADS_COUNT_INCLUDING_DELETED: "api/lead-project-companies/leads/count-including-deleted",
    GET_PROJECT_COUNT_BY_STATUS: "api/lead-project-companies/projects/overview/status-count",
    GET_PROJECT_COUNT_BY_SERVICES: "api/lead-project-companies/projects/overview/services-count",
    GET_PROJECT_COUNT_BY_TEAM: "api/lead-project-companies/projects/overview/teams-count",
    GET_PROJECT_COUNT_BY_CATEGORY: "api/lead-project-companies/projects/overview/category-count",
    GET_PROJECT_COUNT_BY_SUBCATEGORY: "api/lead-project-companies/projects/overview/subcategory-count",
    GET_PROJECT_COUNT_BY_STATUS_YEARLY: "api/lead-project-companies/projects/overview/status-yearly-count",
    GET_PROJECT_COUNT_BY_LOCATION: "api/lead-project-companies/projects/overview/location-count",
    GET_COMPANY_COUNT_BY_TYPE: "api/lead-project-companies/company/overview/type-count",
    GET_CONTACT_COUNT_BY_ROLES: "api/lead-project-companies/company/overview/contacts-count-by-role",
    GET_COMPANY_COUNT_BY_STATUS: "api/lead-project-companies/company/overview/status-count",
    GET_COMPANY_COUNT_BY_LOCATION_AND_STATUS: "api/lead-project-companies/company/overview/location-count",
    GET_UPCOMING_CONTACTS_BIRTHDAYS: "api/lead-project-companies/company/overview/upcoming-contacts-birthdays",
    GET_TOP_COMPANIES_BY_ALL_RATING_FACTOR: "api/lead-project-companies/company/overview/companies-by-all-rating",
    GET_TOP_COMPANIES_BY_RATING_FACTOR: "api/lead-project-companies/company/overview/companies-by-rating/:id",

    GET_ALL_TEAMS: "api/lead-project-companies/projects/teams",
    CREATE_TEAM_WITH_MEMBERS: "api/lead-project-companies/projects/teams/with-members",
    GET_TEAM_BY_ID: "api/lead-project-companies/projects/teams/:id",
    CREATE_TEAM: "api/lead-project-companies/projects/teams",
    UPDATE_TEAM_BY_ID: "api/lead-project-companies/projects/teams/:id",
    DELETE_TEAM_BY_ID: "api/lead-project-companies/projects/teams/:id",

    GET_ALL_TEAMS_MEMBERS: "api/lead-project-companies/projects/members",
    DELETE_MEMBER: 'api/lead-project-companies/members/:id',
    UPDATE_MEMBER_ROLE: 'api/lead-project-companies/members/:id/role',
    CREATE_MULTIPLE_TEAMS_MEMBERS: 'api/lead-project-companies/many',

    GET_ALL_PROJECTS: 'api/lead-project-companies/projects',
    GET_PROJECT_COUNT_FOR_PREFIX: "api/lead-project-companies/projects/count-for-prefix",
    GET_PROJECT_BY_ID: 'api/lead-project-companies/projects/:id',
    CREATE_PROJECT: 'api/lead-project-companies/projects',
    UPDATE_PROJECT: 'api/lead-project-companies/projects/:id',
    GET_ALL_PROJECT_DATA_FOR_OVERVIEW_BY_ID: "api/lead-project-companies/projects/overview-all-data/:id",
    DELETE_PROJECT: 'api/lead-project-companies/projects/:id',

    GET_PROJECTS_BY_COMPANY_ID: "api/lead-project-companies/projects/company/:companyId",
    GET_RATING_BY_COMPANY_ID: "api/lead-project-companies/company/rating/:companyId",
    GET_LEADS_BY_COMPANY_ID: "api/lead-project-companies/company/leads/:companyId",

    GET_ALL_LEAD_STATUSES: "api/lead-project-companies/lead-statuses",
    GET_LEAD_STATUS_BY_ID: "api/lead-project-companies/lead-statuses/:id",
    CREATE_LEAD_STATUS: "api/lead-project-companies/lead-statuses",
    UPDATE_LEAD_STATUS: "api/lead-project-companies/lead-statuses/:id",
    DELETE_LEAD_STATUS: "api/lead-project-companies/lead-statuses/:id",

    GET_ALL_LEAD_REFERRAL_TYPES: "api/lead-project-companies/lead-referral-types",
    GET_LEAD_REFERRAL_TYPE_BY_ID: "api/lead-project-companies/lead-referral-types/:id",
    CREATE_LEAD_REFERRAL_TYPE: "api/lead-project-companies/lead-referral-types",
    UPDATE_LEAD_REFERRAL_TYPE: "api/lead-project-companies/lead-referral-types/:id",
    DELETE_LEAD_REFERRAL_TYPE: "api/lead-project-companies/lead-referral-types/:id",

    GET_ALL_LEAD_DIRECT_SOURCES: "api/lead-project-companies/lead-direct-sources",
    GET_LEAD_DIRECT_SOURCE_BY_ID: "api/lead-project-companies/lead-direct-sources/:id",
    CREATE_LEAD_DIRECT_SOURCE: "api/lead-project-companies/lead-direct-sources",
    UPDATE_LEAD_DIRECT_SOURCE: "api/lead-project-companies/lead-direct-sources/:id",
    DELETE_LEAD_DIRECT_SOURCE: "api/lead-project-companies/lead-direct-sources/:id",

    GET_ALL_PROJECT_CATEGORIES: "api/lead-project-companies/project-categories",
    GET_PROJECT_CATEGORY_BY_ID: "api/lead-project-companies/project-categories/:id",
    CREATE_PROJECT_CATEGORY: "api/lead-project-companies/project-categories",
    UPDATE_PROJECT_CATEGORY: "api/lead-project-companies/project-categories/:id",
    DELETE_PROJECT_CATEGORY: "api/lead-project-companies/project-categories/:id",

    GET_ALL_PROJECT_SUBCATEGORIES: "api/lead-project-companies/project-subcategories",
    GET_PROJECT_SUBCATEGORY_BY_ID: "api/lead-project-companies/project-subcategories/:id",
    CREATE_PROJECT_SUBCATEGORY: "api/lead-project-companies/project-subcategories",
    UPDATE_PROJECT_SUBCATEGORY: "api/lead-project-companies/project-subcategories/:id",
    DELETE_PROJECT_SUBCATEGORY: "api/lead-project-companies/project-subcategories/:id",

    GET_ALL_PROJECT_SERVICES: "api/lead-project-companies/project-services",
    GET_PROJECT_SERVICE_BY_ID: "api/lead-project-companies/project-services/:id",
    CREATE_PROJECT_SERVICE: "api/lead-project-companies/project-services",
    UPDATE_PROJECT_SERVICE: "api/lead-project-companies/project-services/:id",
    DELETE_PROJECT_SERVICE: "api/lead-project-companies/project-services/:id",

    GET_ALL_PROJECT_STATUSES: "api/lead-project-companies/project-statuses",
    GET_PROJECT_STATUS_BY_ID: "api/lead-project-companies/project-statuses/:id",
    CREATE_PROJECT_STATUS: "api/lead-project-companies/project-statuses",
    UPDATE_PROJECT_STATUS: "api/lead-project-companies/project-statuses/:id",
    DELETE_PROJECT_STATUS: "api/lead-project-companies/project-statuses/:id",

    GET_ALL_STAKEHOLDER_SERVICES: "api/lead-project-companies/stakeholder-services",
    GET_STAKEHOLDER_SERVICE_BY_ID: "api/lead-project-companies/stakeholder-services/:id",
    CREATE_STAKEHOLDER_SERVICE: "api/lead-project-companies/stakeholder-services",
    UPDATE_STAKEHOLDER_SERVICE: "api/lead-project-companies/stakeholder-services/:id",
    DELETE_STAKEHOLDER_SERVICE: "api/lead-project-companies/stakeholder-services/:id",

    GET_ALL_CLIENT_TYPES: "api/lead-project-companies/client-types",
    GET_CLIENT_TYPE_BY_ID: "api/lead-project-companies/client-types/:id",
    CREATE_CLIENT_TYPE: "api/lead-project-companies/client-types",
    UPDATE_CLIENT_TYPE: "api/lead-project-companies/client-types/:id",
    DELETE_CLIENT_TYPE: "api/lead-project-companies/client-types/:id",

    GET_ALL_COMPANY_TYPES: "api/lead-project-companies/company-types",
    GET_COMPANY_TYPE_BY_ID: "api/lead-project-companies/company-types/:id",
    CREATE_COMPANY_TYPE: "api/lead-project-companies/company-types",
    UPDATE_COMPANY_TYPE: "api/lead-project-companies/company-types/:id",
    DELETE_COMPANY_TYPE: "api/lead-project-companies/company-types/:id",

    GET_ALL_CONTACT_ROLE_TYPES: "api/lead-project-companies/contact-role-types",
    GET_CONTACT_ROLE_TYPE_BY_ID: "api/lead-project-companies/contact-role-types/:id",
    CREATE_CONTACT_ROLE_TYPE: "api/lead-project-companies/contact-role-types",
    UPDATE_CONTACT_ROLE_TYPE: "api/lead-project-companies/contact-role-types/:id",
    DELETE_CONTACT_ROLE_TYPE: "api/lead-project-companies/contact-role-types/:id",

    GET_ALL_LEAD_BRANCHES: 'api/lead-project-companies/lead-branches',
    GET_LEAD_BRANCH_BY_ID: 'api/lead-project-companies/lead-branches/:id',
    CREATE_LEAD_BRANCH: 'api/lead-project-companies/lead-branches',
    UPDATE_LEAD_BRANCH: 'api/lead-project-companies/lead-branches/:id',
    DELETE_LEAD_BRANCH: 'api/lead-project-companies/lead-branches/:id',
    GET_LEAD_BRANCHES_BY_COMPANY_ID: 'api/lead-project-companies/lead-branches/company/:companyId',

    GET_LEADS_BY_STATUS_ANALYTICS: "api/lead-project-companies/lead-analytics/status",
    GET_LEADS_BY_SERVICE_ANALYTICS: "api/lead-project-companies/lead-analytics/service",
    GET_LEADS_BY_PROJECT_CATEGORY_ANALYTICS: "api/lead-project-companies/lead-analytics/project-category",
    GET_LEADS_BY_SUBCATEGORY_ANALYTICS: "api/lead-project-companies/lead-analytics/subcategory",
    GET_LEADS_BY_DIRECT_SOURCE_ANALYTICS: "api/lead-project-companies/lead-analytics/direct-source",
    GET_LEADS_BY_REFERRAL_SOURCE_ANALYTICS: "api/lead-project-companies/lead-analytics/referral-source",
    GET_LEADS_BY_SOURCE_ANALYTICS: "api/lead-project-companies/lead-analytics/source",
    GET_LEADS_BY_COMPANY_TYPE_ANALYTICS: "api/lead-project-companies/lead-analytics/company-type",
    GET_MONTHLY_TOP_LEADS: "api/lead-project-companies/lead-analytics/monthly-top-leads",
    GET_MONTHLY_LEAD_ANALYTICS: "api/lead-project-companies/lead-analytics/monthly",
    GET_MONTHLY_TARGETS: "api/lead-project-companies/lead-analytics/monthly-targets",
    GET_DAILY_MONTHLY_RUN_RATE: "api/lead-project-companies/lead-analytics/daily-monthly-run-rate",
    GET_MONTHLY_LEADS_BY_REFERRAL_SOURCES: "api/lead-project-companies/lead-analytics/monthly-leads-referral-sources",
    GET_MONTHLY_LEADS_BY_DIRECT_SOURCES: "api/lead-project-companies/lead-analytics/monthly-leads-direct-sources",
    GET_LEADS_BY_LOCATION_ANALYTICS: "api/lead-project-companies/lead-analytics/location",

    GET_PROJECTS_BY_CONTACT_ID: "api/lead-project-companies/projects/contact/:id",
    GET_PROJECT_COUNT_BY_COMPANY_TYPE: "api/lead-project-companies/projects/overview/company-type-count",
    GET_PROJECT_COUNT_BY_COMPANY_TYPE_YEARLY: "api/lead-project-companies/projects/overview/company-type-yearly-count",
}

export const CLIENT_COMPANIES = {
    GET_ALL_COMPANY_RATINGS: "api/lead-project-companies/client-companies/company-ratings",
    GET_COMPANY_RATING_BY_ID: "api/lead-project-companies/client-companies/company-ratings/:id",
    UPDATE_COMPANY_RATING: "api/lead-project-companies/client-companies/company-ratings/:id",
    DELETE_COMPANY_RATING: "api/lead-project-companies/client-companies/company-ratings/:id",
    CREATE_COMPANY_RATING: "api/lead-project-companies/client-companies/company-ratings",

    GET_ALL_RATING_FACTORS: "api/lead-project-companies/client-companies/rating-factor",
    GET_RATING_FACTOR_BY_ID: "api/lead-project-companies/client-companies/rating-factor/:id",
    CREATE_RATING_FACTOR: "api/lead-project-companies/client-companies/rating-factor",
    UPDATE_RATING_FACTOR: "api/lead-project-companies/client-companies/rating-factor/:id",
    DELETE_RATING_FACTOR: "api/lead-project-companies/client-companies/rating-factor/:id",

    GET_ALL_LEADS: "api/lead-project-companies/client-companies/leads",
    GET_LEAD_BY_ID: "api/lead-project-companies/client-companies/leads/:id",
    CREATE_LEAD: "api/lead-project-companies/client-companies/leads",
    UPDATE_LEAD: "api/lead-project-companies/client-companies/leads/:id",
    DELETE_LEAD: "api/lead-project-companies/client-companies/leads/:id",

    GET_ALL_CLIENT_COMPANIES: "api/lead-project-companies/client-companies",
    GET_CLIENT_COMPANY_BY_ID: "api/lead-project-companies/client-companies/:id",
    CREATE_CLIENT_COMPANY: "api/lead-project-companies/client-companies",
    UPDATE_CLIENT_COMPANY: "api/lead-project-companies/client-companies/:id",
    DELETE_CLIENT_COMPANY: "api/lead-project-companies/client-companies/:id",

    GET_ALL_CONTACTS: "api/lead-project-companies/client-companies/contacts",
    GET_CONTACT_BY_ID: "api/lead-project-companies/client-companies/contacts/:id",
    CREATE_CONTACT: "api/lead-project-companies/client-companies/contacts",
    UPDATE_CONTACT: "api/lead-project-companies/client-companies/contacts/:id",
    DELETE_CONTACT: "api/lead-project-companies/client-companies/contacts/:id",
    GET_CONTACTS_BY_COMPANY_ID: "api/lead-project-companies/client-companies/contacts/company/:companyId",

    GET_ALL_ADDITIONAL_DETAILS: "api/lead-project-companies/client-companies/leads/additional-details",
    GET_ADDITIONAL_DETAILS_BY_ID: "api/lead-project-companies/client-companies/leads/additional-details/:id",
    CREATE_ADDITIONAL_DETAILS: "api/lead-project-companies/client-companies/leads/additional-details",
    UPDATE_ADDITIONAL_DETAILS: "api/lead-project-companies/client-companies/leads/additional-details/:id",
    CREATE_ADDITIONAL_DETAILS_MANY: "api/lead-project-companies/client-companies/leads/additional-details/many",
    UPDATE_ADDITIONAL_DETAILS_MANY: "api/lead-project-companies/client-companies/leads/additional-details/many/:leadId",
    GET_ADDITIONAL_DETAILS_BY_LEAD_ID: "api/lead-project-companies/client-companies/leads/additional-details/lead/:leadId",

    UPDATE_COMPANY_RATING_BY_COMPANY_ID: "api/lead-project-companies/client-companies/company-ratings/company/:companyId",

    GET_ALL_LEAD_CANCELLATION_REASONS: "api/lead-project-companies/client-companies/lead-cancellation-reasons",
    GET_LEAD_CANCELLATION_REASON_BY_ID: "api/lead-project-companies/client-companies/lead-cancellation-reasons/:id",
    CREATE_LEAD_CANCELLATION_REASON: "api/lead-project-companies/client-companies/lead-cancellation-reasons",
    UPDATE_LEAD_CANCELLATION_REASON: "api/lead-project-companies/client-companies/lead-cancellation-reasons/:id",
    DELETE_LEAD_CANCELLATION_REASON: "api/lead-project-companies/client-companies/lead-cancellation-reasons/:id",

    GET_ALL_CONTACT_STATUSES: 'api/lead-project-companies/client-companies/contact-statuses',
    GET_CONTACT_STATUS_BY_ID: 'api/lead-project-companies/client-companies/contact-statuses/:id',
    CREATE_CONTACT_STATUS: 'api/lead-project-companies/client-companies/contact-statuses',
    UPDATE_CONTACT_STATUS: 'api/lead-project-companies/client-companies/contact-statuses/:id',
    DELETE_CONTACT_STATUS: 'api/lead-project-companies/client-companies/contact-statuses/:id',

}

export const COMPANY_SERVICES = {
    CREATE: 'api/lead-project-companies/company/services',
    UPDATE: 'api/lead-project-companies/company/services/:id',
    DELETE: 'api/lead-project-companies/company/services/:id',
    GET_ALL: 'api/lead-project-companies/company/services',
};

export const SUBCOMPANY_SERVICES = {
    CREATE: 'api/lead-project-companies/sub-company/:subCompanyId/services',
    UPDATE: 'api/lead-project-companies/sub-company/:subCompanyId/services',
    DELETE: 'api/lead-project-companies/sub-company/:subCompanyId/services/:id',
    GET_ALL: 'api/lead-project-companies/sub-company/:subCompanyId/services',
};

export const TASKS = {
    CREATE_TASK_STATUS: "api/task-and-time/task-statuses",
    GET_ALL_TASK_STATUSES: "api/task-and-time/task-statuses",
    UPDATE_TASK_STATUS: "api/task-and-time/task-statuses",

    CREATE_TASK_PRIORITY: "api/task-and-time/task-priorities",
    GET_ALL_TASK_PRIORITIES: "api/task-and-time/task-priorities",
    UPDATE_TASK_PRIORITY: "api/task-and-time/task-priorities",

    CREATE_PRESET_TASKS_STATUS: "api/task-and-time/task-persest",
    GET_ALL_PRESET_TASKS_STATUSES: "api/task-and-time/task-persest",
    UPDATE_PRESET_TASKS_STATUS: "api/task-and-time/task-persest",
    DELETE_PRESET_TASKS_STATUS: "api/task-and-time/task-persest",

    GET_ALL_TASKS: "api/task-and-time/task",
    CREATE_TASK: "api/task-and-time/task",
    UPDATE_TASK: "api/task-and-time/task",
    DELETE_TASK: "api/task-and-time/task",
    UPDATE_TASK_STATUS_BY_TASKID: "/api/task-and-time/task/:taskId",
    GET_TASKS_BY_PROJECT_ID: "/api/task-and-time/task/project/:projectId",
    GET_TIMESHEETS_BY_PROJECTID: "/api/task-and-time/time-sheets/project/:projectId?billable=:billable",
    GET_TIMESHEETS_BY_PROJECTID_WITH_COST: "/api/task-and-time/time-sheets/project/:projectId/with-costing?billable=:billable",
    GET_ALL_TIME_SHEETS_BY_START_DATE_END_DATE: "api/task-and-time/time-sheets",
    GET_TIME_SHEETS_BY_EMPLOYEE_ID: "api/task-and-time/time-sheets/employee",
    GET_TIMESHEETS_EMPLOYEEID_STARTDATE_ENDDATE: "api/task-and-time/time-sheets/employee/:employeeId/range?startDate=:startDate&endDate=:endDate",
    GET_TIMESHEET_BY_ID: "api/task-and-time/time-sheets/:id",
    GET_TIMESHEETS_BY_TASKID: "api/task-and-time/time-sheets/task/:taskId",
    EDIT: "api/task-and-time/task/time-sheet/:id",
    DELETE: "api/task-and-time/task/time-sheet/:id",
    CREATE: "api/task-and-time/task/time-sheet",
    GET_ALL_TASKS_WITH_METRICS: "/api/task-and-time/tasks/metrics",
    UPDATE: "api/task-and-time/task/time-sheet/:id",

    GET_TASK_BY_ID: "/api/task-and-time/task/:id",
    GET_TASKS_STATUS_START_END_DATE: "/api/task-and-time/tasks/status/start-end-date?startDate=:startDate&endDate=:endDate",
    GET_ALL_PROJECT_ONLY_SELECTED_FIELDS: "/api/task-and-time/task/get-all-project-only-selected-fields",
}

export const ORGANIZATION_CONFIGURATION = {
    CREATE: '/api/organization-configurations',
    GET_ALL: '/api/organization-configurations',
    GET_BY_ID: '/api/organization-configurations/:id',
    GET_BY_TYPE: '/api/organization-configurations/type/:type',
    UPDATE: '/api/organization-configurations/:id',
    DELETE: '/api/organization-configurations/:id',
};

export const EMPLOYEE_CONFIGURATION = {
    CREATE: '/api/employee-configurations',
    GET_ALL: '/api/employee-configurations',
    GET_BY_ID: '/api/employee-configurations/:id',
    GET_BY_TYPE: '/api/employee-configurations/type/:type',
    UPDATE: '/api/employee-configurations/:id',
    DELETE: '/api/employee-configurations/:id',
};