import React, { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Box, Pagination, Stack, Typography } from "@mui/material";
import { TRIO } from "@app/modules/common/components/ui";
import { formatCurrencyDecimal } from "@utils/currency";
import { formatDate } from "@utils/dateFormats";
import { getRevenueReport, type RevenueTableRow } from "@services/billingReports";
import { BillingPageHeader, BillingStatsCard, BillingTable, type BillingColumn } from "../components";
import ReportChart from "./shared/ReportChart";
import ReportFilterBar, { EMPTY_REPORT_FILTERS, type ReportFilterValues } from "./shared/ReportFilterBar";
import ReportExportToolbar from "./shared/ReportExportToolbar";
import ColumnSelector, { useColumnVisibility } from "./shared/ColumnSelector";
import SavedFiltersMenu from "./shared/SavedFiltersMenu";
import { useSavedFilters } from "./shared/useSavedFilters";

const PAGE_SIZE = 25;

/**
 * Revenue Report — what Tax Invoices have generated, by period, client and project.
 */
const RevenueReportPage: React.FC = () => {
  const navigate = useNavigate();
  const [filters, setFilters] = useState<ReportFilterValues>(EMPTY_REPORT_FILTERS);
  const [page, setPage] = useState(1);
  const { saved, save, remove } = useSavedFilters<ReportFilterValues>("revenue");

  const params = useMemo(() => ({
    search: filters.search || undefined,
    dateFrom: filters.dateFrom || undefined,
    dateTo: filters.dateTo || undefined,
    minAmount: filters.minAmount ? Number(filters.minAmount) : undefined,
    maxAmount: filters.maxAmount ? Number(filters.maxAmount) : undefined,
    page, pageSize: PAGE_SIZE,
  }), [filters, page]);

  const { data, isLoading } = useQuery({
    queryKey: ["reports", "revenue", params],
    queryFn: () => getRevenueReport(params),
  });

  const stats = data?.stats;
  const rows = data?.table.rows ?? [];
  const pageCount = data ? Math.max(1, Math.ceil(data.table.total / data.table.pageSize)) : 1;

  const allColumns = [
    { key: "invoiceNumber", header: "Invoice No" },
    { key: "project", header: "Project" },
    { key: "client", header: "Client" },
    { key: "invoiceDate", header: "Invoice Date" },
    { key: "taxableAmount", header: "Taxable Amount" },
    { key: "gstAmount", header: "GST" },
    { key: "totalAmount", header: "Total" },
    { key: "status", header: "Status" },
    { key: "generatedBy", header: "Generated By" },
  ];
  const { isVisible, toggle } = useColumnVisibility(allColumns.map((c) => c.key), ["invoiceNumber", "totalAmount"]);

  const rawColumns: (BillingColumn<RevenueTableRow> | false)[] = [
    {
      key: "invoiceNumber", header: "Invoice No", width: 150,
      render: (row) => <Typography sx={{ fontSize: 12.5, fontWeight: 700 }}>{row.invoiceNumber}</Typography>,
      searchValue: (row) => row.invoiceNumber, sortValue: (row) => row.invoiceNumber,
    },
    isVisible("project") && {
      key: "project", header: "Project",
      render: (row) => (
        <Typography
          sx={{ fontSize: 12.5, fontWeight: 600, cursor: row.leadId ? "pointer" : "default", "&:hover": row.leadId ? { textDecoration: "underline" } : {} }}
          onClick={(e) => { if (row.leadId) { e.stopPropagation(); navigate(`/billing/reports/project?projectId=${row.leadId}`); } }}
        >
          {row.projectName ?? "—"}
        </Typography>
      ),
      searchValue: (row) => row.projectName,
    },
    isVisible("client") && {
      key: "client", header: "Client",
      render: (row) => (
        <Typography
          sx={{ fontSize: 12.5, cursor: row.companyId ? "pointer" : "default", "&:hover": row.companyId ? { textDecoration: "underline" } : {} }}
          onClick={(e) => { if (row.companyId) { e.stopPropagation(); navigate(`/billing/reports/client?clientId=${row.companyId}`); } }}
        >
          {row.clientName ?? "—"}
        </Typography>
      ),
      searchValue: (row) => row.clientName,
    },
    isVisible("invoiceDate") && {
      key: "invoiceDate", header: "Invoice Date", width: 130,
      render: (row) => formatDate(row.invoiceDate),
      sortValue: (row) => row.invoiceDate,
    },
    isVisible("taxableAmount") && {
      key: "taxableAmount", header: "Taxable Amount", width: 140, align: "right",
      render: (row) => formatCurrencyDecimal(row.taxableAmount),
      sortValue: (row) => row.taxableAmount,
    },
    isVisible("gstAmount") && {
      key: "gstAmount", header: "GST", width: 110, align: "right",
      render: (row) => formatCurrencyDecimal(row.gstAmount),
      sortValue: (row) => row.gstAmount,
    },
    {
      key: "totalAmount", header: "Total", width: 140, align: "right",
      render: (row) => <Typography sx={{ fontSize: 12.5, fontWeight: 700 }}>{formatCurrencyDecimal(row.totalAmount)}</Typography>,
      sortValue: (row) => row.totalAmount,
    },
    isVisible("status") && {
      key: "status", header: "Status", width: 110,
      render: (row) => row.status,
    },
    isVisible("generatedBy") && {
      key: "generatedBy", header: "Generated By", width: 150,
      render: (row) => row.generatedBy ?? "—",
    },
  ];
  const columns = rawColumns.filter((c): c is BillingColumn<RevenueTableRow> => Boolean(c));

  return (
    <Box sx={{ maxWidth: 1600, mx: "auto", pb: 4 }}>
      <BillingPageHeader
        icon="chart-line-up" trio={TRIO.green} title="Revenue Report"
        description="Invoiced revenue by period, project and client."
      />

      <Box sx={{ display: "grid", gap: 1.25, mb: 2, gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))" }}>
        <BillingStatsCard label="Total Revenue" icon="dollar" trio={TRIO.green} value={formatCurrencyDecimal(stats?.totalRevenue ?? 0)} />
        <BillingStatsCard label="This Month" icon="calendar" trio={TRIO.blue} value={formatCurrencyDecimal(stats?.revenueThisMonth ?? 0)} />
        <BillingStatsCard label="This Year" icon="calendar-tick" trio={TRIO.purple} value={formatCurrencyDecimal(stats?.revenueThisYear ?? 0)} />
        <BillingStatsCard label="Avg Invoice" icon="chart-pie-simple" trio={TRIO.amber} value={formatCurrencyDecimal(stats?.averageInvoiceValue ?? 0)} />
        <BillingStatsCard label="Highest Invoice" icon="arrow-up" trio={TRIO.cyan} value={formatCurrencyDecimal(stats?.highestInvoice ?? 0)} />
        <BillingStatsCard label="Lowest Invoice" icon="arrow-down" trio={TRIO.slate} value={formatCurrencyDecimal(stats?.lowestInvoice ?? 0)} />
      </Box>

      <Box sx={{ display: "grid", gap: 1.25, mb: 2, gridTemplateColumns: { xs: "1fr", lg: "2fr 1fr" } }}>
        <ReportChart title="Monthly Revenue Trend" type="area" data={data?.charts.monthlyTrend ?? []} height={280} />
        <ReportChart title="Revenue by Project Type" subtitle="Top projects" type="donut" data={(data?.charts.byProject ?? []).slice(0, 6)} height={280} />
      </Box>
      <Box sx={{ display: "grid", gap: 1.25, mb: 2, gridTemplateColumns: { xs: "1fr", lg: "1fr 1fr" } }}>
        <ReportChart
          title="Revenue by Client" type="bar" data={data?.charts.byClient ?? []} height={260}
          onSliceClick={(p) => {
            const match = rows.find((r) => r.clientName === p.label);
            if (match?.companyId) navigate(`/billing/reports/client?clientId=${match.companyId}`);
          }}
        />
        <ReportChart title="Revenue by Project" type="bar" data={data?.charts.byProject ?? []} height={260} />
      </Box>

      <ReportFilterBar
        values={filters} onChange={(next) => { setFilters(next); setPage(1); }}
        searchPlaceholder="Search invoice, project, client…"
        onReset={() => { setFilters(EMPTY_REPORT_FILTERS); setPage(1); }}
        extra={
          <Stack direction="row" spacing={0.75}>
            <SavedFiltersMenu saved={saved} onApply={setFilters} onSave={(name) => save(name, filters)} onRemove={remove} />
            <ColumnSelector columns={allColumns} isVisible={isVisible} onToggle={toggle} alwaysOn={["invoiceNumber", "totalAmount"]} />
            <ReportExportToolbar
              data={rows} filename="revenue-report" title="Revenue Report" showTotals
              fetchAll={async () => (await getRevenueReport({ ...params, page: 1, pageSize: 1000 })).table.rows}
              columns={[
                { key: "invoiceNumber", header: "Invoice No" },
                { key: "projectName", header: "Project" },
                { key: "clientName", header: "Client" },
                { key: "invoiceDate", header: "Invoice Date", format: (v) => formatDate(v) },
                { key: "taxableAmount", header: "Taxable Amount", type: "currency", showTotal: true },
                { key: "gstAmount", header: "GST", type: "currency", showTotal: true },
                { key: "totalAmount", header: "Total", type: "currency", showTotal: true },
                { key: "status", header: "Status" },
                { key: "generatedBy", header: "Generated By" },
              ]}
            />
          </Stack>
        }
      />

      <BillingTable
        rows={rows}
        columns={columns}
        getRowId={(row) => row.id}
        loading={isLoading}
        emptyTitle="No invoices yet"
        emptyDescription="Revenue appears here once Tax Invoices are generated."
        minWidth={1100}
        pageSize={PAGE_SIZE}
      />

      {data && pageCount > 1 && (
        <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mt: 2 }}>
          <Typography sx={{ fontSize: 12, color: "text.secondary" }}>{data.table.total} invoices</Typography>
          <Pagination size="small" count={pageCount} page={page} onChange={(_e, next) => setPage(next)} />
        </Stack>
      )}
    </Box>
  );
};

export default RevenueReportPage;
